### ISSUE TITLE
Remove abstract cms component

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1048]
The AbstractCmsComponent has been deprecated, so we should get ride of it.

**Comment by ravivarma4142** [comment]
![AbstractCmsComponent](https://user-images.githubusercontent.com/34150393/60484904-b9679680-9cb8-11e9-8251-d7109e0902aa.jpg)
![CmsComponentData](https://user-images.githubusercontent.com/34150393/60484905-b9679680-9cb8-11e9-9ade-f786cc1258b1.jpg)


Instead of AbstractCmsComponent(as its not available in the storefront) I am replaced with CmsComponentData I am getting component.template is not defined error.

Can you please help me.

**Comment by JaveedShaiks** [comment]
Am also same error. Am trying to access this.uid 

since CmsComponentData retruning uid and data$. both uid adn data$ are undefined

**Comment by JaveedShaiks** [comment]
It worked. Below are working changes

`export class customComponent implements OnInit {
ComponentData = {};
constructor(
public component: CmsComponentData
) {}

ngOnInit(): void {
this.getText();
}
public getText(): any {
return this.component.data$.subscribe(data => {
return this.ComponentData = data;
})
}
}`
