### ISSUE TITLE
refactor product carousel logic

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1049]
- the carousel logic should be moved to a service
- ~~the carousel could leverage the new breakpoint service~~ the carousel uses the component width, which allows the component to be wrapped in a grid system (i.e. in a 50% width of screen).

**Comment by kacperknapik** [comment]
see `search-box` which currently works as an example.
todo:
- component should be as thin as possible (as little logic/methods/abstract layers as possible - move those to the newly created service)
- component should use its service logic (eg. `this.service.getFoo()`, instead of `this.userService.getFoo()`)

**Comment by kacperknapik** [comment]
The logic has been moved to component's service. Carousel works well, even when the container width is lower that 100%. All good
