### ISSUE TITLE
[Master] API calls should use 'current' instead of emails

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1092]
OCC team is planning to add the ability to reference a user with Customer.customerId instead of by email. We should implement this for our launch and provide a configuration option to be backwards compatible (meaning if you want you can go back to using emails as the ID).

Depends on this ticket, merged Apr24: RAY-227
Contact is Pawel Gawlowski

Sub tasks to achieve the goal:
- [x] GH-2584 - Use 'current' instead of the email in the occ urls - step 1
- [x] GH-2498 - Remove userId arguments in Checkout Facade
- [x] GH-2672 - Remove userId arguments in User Facade - Update User Details
- [x] GH-2674 - Remove userId arguments in User Facade - Update Email
- [x] GH-2665 - Remove userId arguments in User Facade - Close Account
- [x] GH-2509 - Remove userId arguments in User Facade - Update Password
- [x] GH-2510 - Remove userId arguments in User Facade - Order History functions
- [x] GH-2511 - Remove userId arguments in User Facade - Payment functions
- [x] GH-2512 - Remove userId arguments in User Facade - Address functions
- [x] GH-2513 - Remove userId arguments in User Facade - Consent Management
- [x] GH-2763 - Remove userId arguments in User Facade - Load User Details

~~GH-2497 - Add a function to retrieve the userId according to the configuration~~
~~GH-2499 - Use the getUserId function in the CartFacade~~

**Comment by plabadie** [comment]
After discussion with @tobi-or-not-tobi @Matejk00 and @frankgrupe, we considered multiple scenarios and decided the better option is to use an "HTTP Interceptor that adds the proper user id in each request"

See scenario B
https://wiki.hybris.com/display/spar/OCC+uses+customer+Id

**Comment by plabadie** [comment]
After discussion with @LTiger14, it appears that we don't foresee a conflict between the solution for the the "user id interceptor" and the configurable routes feature.

**Comment by plabadie** [comment]
Update: After spiking, investigation and internal team discussion, we’re going with scenario “D” to implement the configurable usage of the `customerId` in  occ calls. (see https://wiki.hybris.com/display/spar/OCC+uses+customer+Id)

The Scenario “D”  delivers on the overall requirements and the software architecture preference for removing the userId argument from the facade functions and reducing the logic needed in UI components.

The twist in this scenario is that instead of using an http interceptor, the userId lookup happens essentially inside the facade layer.  The userId is passed down to rest of the core lib layers.  Therefore we don’t need to refactor the rest of the core lib code because the functions signature remain intact.

As far as I know, it will play well with the upcoming ASM implementation and the refactoring scope is manageable.

**Comment by plabadie** [comment]
We decided to simplify the solution and go with scenario "E" instead.
Essentially, we will use the user id `current` for now.

https://wiki.hybris.com/display/spar/OCC+uses+customer+Id
