### ISSUE TITLE
Application Caching architecture

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1169]
We like to document the caching architecture as it contributes to the overall scalability of the commerce implementation.

**Comment by tobi-or-not-tobi** [comment]
![image](https://user-images.githubusercontent.com/4745807/52336711-e6639600-2a05-11e9-9e6c-00ec46e3ce54.png)

**Comment by tobi-or-not-tobi** [comment]
**Static files caching**
1. static files are uniquely named during the build process, driven by the content hashes
2. media (i.e. product images) are also exposed with a unique URL
3. static files and media can have a far-future-expiration header (in cache-control) as they're unique
4. backend calls (OCC) can also be cached, but different expiration headers are used per endpoint (i.e. short TTL for price data, mid-term TTL for CMS data)

![image](https://user-images.githubusercontent.com/4745807/52336835-42c6b580-2a06-11e9-816c-a23b2b7d9b0f.png)

**Comment by tobi-or-not-tobi** [comment]
**Edge Caching (CDN)**
Both static files, media and backend responses can be cached on a CDN. 
Pull strategy is recommended, so that the central cache-control is used to control the  expiry of the edge cache.

![image](https://user-images.githubusercontent.com/4745807/52337219-5b839b00-2a07-11e9-8a6c-b35cf7d13799.png)

**Comment by tobi-or-not-tobi** [comment]
**Server Side Rendering (SSR)**
- SSR is used in the first placed for providing a crawling-response for bots, but the response will also be used at the very first visit of the web client (see PWA features in next session how the SSR response is not used in future interactions). 
- The SSR server wraps the client app in a nodejs (express) server. 
- As long as the response can be represented based on the URL (and additional cookie info), the SSR response can (and should) be stored on the CDN as well. 
- The SSR server will use the backend to generate the view. These backend calls wil go through the same CDN. 
- The generated state in the SSR server will be transferred to the client app in order to avoid rebuilding the state and causing bad experience (flickering).

![image](https://user-images.githubusercontent.com/4745807/52337350-ac938f00-2a07-11e9-917b-533192259d09.png)

**Comment by tobi-or-not-tobi** [comment]
**Cache API (PWA)**
- As soon as the first (SSR driven) response  is loaded in the web client, the service worker will cache resources based on the service worker configuration. 
- The service worker will cache application resources as well as content (OCC responses, images).
- The next visit will be executed based on the cached resources. In addition, the service worker will verify the accuracy of the index.html in order to see if it's the latest version. If there's a new version available, this version will be used on the next visit. 

![image](https://user-images.githubusercontent.com/4745807/52339190-b4096700-2a0c-11e9-89f0-5d4151563c1e.png)
