### ISSUE TITLE
1a. Create new custom auth guard for checkout

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1182]
At the moment the checkout process is blocked by a simple auth guard that checks if the user is signed in. The auth guard should be kept but a new guard should be created for the checkout. 

This guard should redirect to login but should also pass some data to the login page (using the data field https://angular.io/api/router/Route#data). The data field is a key value pair. It should be the key should be "forced" (forced login) and the value true. The login page will be updated to read this in #1387.

This guard should also check if the cart contains a user to see if the user is a "guest". If he is a guest, he should be able to checkout.

This will be the only guard for checkout so it should also allow logged in users through. Therefore, it should reuse some of the logic from auth guard.

### Acceptance criteria
- Checkout only accessible as user or guest user
- If a user has no role and tries to checkout he is redirected to the "guest login" page

**Comment by mirkosoft** [comment]
I have pushed the newly created guard for checkout to the feature branch `feature/GH-1182`.
@LTiger14, @mszczepaniak  please note that we are not going to use `data` for passing the `forced` param. Instead we use the queryParam (`?forced=true`). The reason is that `data` is not mutable as well it will be lost in case of page refresh (we do not keep that in the store also).
As for now I also left the cart user part as we have to wait for #1179, RAY-229
