### ISSUE TITLE
Order of Title listed in the drop down menu

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1416]
## Environment Details

- Spartacus:  Latest dev branch
- Browser: safari

## Steps to Reproduce
1) Go to Register Page
**The order of titles listed is different. Why this order? Why is 'Dr" listed before Mrs, Miss, Ms? Comparison with original acc:**

_SPA:_
<img width="901" alt="spa_register" src="https://user-images.githubusercontent.com/45409515/53348615-65ebd300-38e9-11e9-8936-7a393aa81fe8.png">

_ACC:_
<img width="699" alt="acc_register" src="https://user-images.githubusercontent.com/45409515/53348620-6a17f080-38e9-11e9-8e26-bd3ed62ad1d2.png">

2) Go to the address page (whether it's the shipping address during checkout, or adding a new address from MyAccount-> Address Book)

**Same as above, the order is odd.**

_SPA:_
<img width="897" alt="spa_address" src="https://user-images.githubusercontent.com/45409515/53349542-540b2f80-38eb-11e9-8a42-e9794720c01f.png">
_ACC:_
<img width="682" alt="acc_address" src="https://user-images.githubusercontent.com/45409515/53349546-566d8980-38eb-11e9-81c3-134dffd69430.png">

**Also, the first default line is "None" in spa. Vs, "Title" or "select title"** 

_SPA:_
<img width="675" alt="spa_title" src="https://user-images.githubusercontent.com/45409515/53348738-a2b7ca00-38e9-11e9-8938-abec0b0a2a53.png">
_ACC:_
<img width="680" alt="acc_title" src="https://user-images.githubusercontent.com/45409515/53348741-a51a2400-38e9-11e9-81cf-e7facff8f788.png">

**Comment by kacperknapik** [comment]
I don't really like this solution (https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1599/files#diff-ab2d5a117caa57a53dfcb8e069392b83R28) 

We shouldn't hardcode those values, since we eventually want to have the data to be cms driven + translatable etc.

For now it's fine tho. @KateChuen we agreed that while we don't have the same backend config on all servers, we will stick to `None` title. On one server `title` property is required on the other is optional - this caused problems.
