### ISSUE TITLE
Add support for ProductReferencesComponent

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1421]
Used for upsells and cross sells
ProductReferencesComponent

**Comment by bgambocjaviniar** [comment]
waiting for https://jira.hybris.com/browse/RAY-272 and https://jira.hybris.com/browse/RAY-275

**Comment by bgambocjaviniar** [comment]
PR: GH-2033

**Comment by bgambocjaviniar** [comment]
QA steps:

-Go to backoffice > wcms > contentslot 
-Find Upselling slot
-Under components, add a productreferencescomponent, such as Similar
-Double click Similar, and click the administration tabs. Under reference types, choose similar or accessories as the reference type because if you look at the product-relations.impex in the b2cmodule, those are the only types that are available/setup

-Navigate to one of the items who has a product references found in the product-relations.impex, such as 358639

**Comment by KateChuen** [comment]
Tested on dev2, with reference type "accessories". Able to see the upselling accessories on the storefront. 
<img width="1325" alt="upsellingAcc" src="https://user-images.githubusercontent.com/45409515/58120537-7acbc000-7bd3-11e9-87ff-3286f0161bca.png">

**Comment by Xymmer** [comment]
RAY-319 is in 1905.1
