### ISSUE TITLE
Add copyright information to source files [not needed]

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1619]
We should add a header with copyright info on each file in the code base. This can be done automatically in the pipeline or on local devs.
This is most likely a legal concern.

**Comment by Xymmer** [comment]
Bill to check first if we have to do this for open source

**Comment by Xymmer** [comment]
Bill to contact open source group for answer.
Other open source repos in sap github aren't putting copyright.

**Comment by Xymmer** [comment]
From https://jam4.sapjam.com/wiki/show/i8rCRkXwUSugGCC5ULNpCu

It is not mandatory to include license or copyright headers in each project source file, however, you are free to do so if desired. The use of license and copyright headers may be beneficial as it provides further notice to end users respecting ownership and license requirements that could assist with license compliance. If you desires to use a license or copyright header in your source files please use the following header:

“Copyright (c) 2015 SAP SE or an SAP affiliate company. All rights reserved.
This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file [include link to the LICENSE file in your project repository].”
