### ISSUE TITLE
Refactor storefinder component to CmsComponent with child routes

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#1655]

**Comment by dunqan** [comment]
QA steps:
- check if store finder works (it is now generic cms page)
- check if subroutes for store finder works (they are implemented as routes with cms component)

**Comment by KateChuen** [comment]
Tested on dev17. 

- [X] Store finder works

- [X] Verified that clicking on 
- _Find a store_ goes to http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/store-finder
- _Find store_ goes to http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/store-finder/find?query=
- _Use my location_ goes to http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/store-finder/find?useMyLocation=true
- _View all stores_ goes to http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/store-finder/view-all
- _Country Japan_ goes to http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/store-finder/country/JP
- _A store_ goes to http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/store-finder/country/JP/region//Kobe%20Bay%20Sheraton%20Hotel%20and%20Towers


- [ ] Cannot enter the deep links by hand, they go to notFound (known issue that needs to be fixed in the backend. Already a ticket for that). For eg, if i type in http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/store-finder/view-all, it goes to notFound page
![404Store](https://user-images.githubusercontent.com/45409515/55010285-529c5800-4fba-11e9-9107-66ae9ad8781d.png)
