### ISSUE TITLE
[test] Some Smartedit issues 

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1677]
There are 3 tabs in smartedit: Hompage, Pages, Navigation

1. Homepage

It works! But, there are some known issues:
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1473 (not get the reason yet)
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/818 (we know the reason. Stepan is investigating.)

2. Pages

- Normal Content Pages (e.g. FAQ):  work!

- Account Content Pages: We can see the cms pages. But since anonymous users cannot access account pages, there are some errors shown in the pages. 
![Screen Shot 2019-03-14 at 9 17 02 AM](https://user-images.githubusercontent.com/44440575/54366785-a23c6480-4647-11e9-9036-7cac1a914b84.png)

Customers should be redirected to login page.

Talked to @tobi-or-not-tobi : we can do this https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1678

- Product/Category Pages: We only can see the cms pages, but we need redirect to the preview product/category page.
Ticket was created: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1621
This ticket is blocked by https://jira.hybris.com/browse/RAY-259 and #1344. If we don't want to wait, we can hard-code the preview product/category code in SPA.

3. Navigation
Not fully tested. But, it does not launch SPA. So, it should work as before.

**Comment by Xymmer** [comment]
bill to check what else to do from this ticket

**Comment by KateChuen** [comment]
Retested on dev2 (updated)
1. Homepage
#1473 (not get the reason yet) -> FIXED
![overlay1](https://user-images.githubusercontent.com/45409515/57325481-1b03ee00-70d8-11e9-9ff6-039e4b290267.png)

#818 -> FIXED (no longer a href="#")
![818](https://user-images.githubusercontent.com/45409515/57325297-bb0d4780-70d7-11e9-85bc-aa115d456eda.png)

2. Pages
Account Content Pages: As Wei mentioned, since user doesn't have access to the page, we get 401 back, which makes sense. 
But like Wei mentioned, Customers should be redirected to login page. -> This is **not** currently the case.
