### ISSUE TITLE
Improve configuration structure for backends

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1784]
On our path to make Spartacus more adaptable for other backends and third-party systems, we like to make our configuration more specific. We currently allow to configure the Commerce baseUrl and endpoint configuration in a structure that is not semantic enough to understand. Moreover, it is too generic and wil not scale. 

Currently we have these items in the root of the config:
```
server: {
    baseUrl: environment.occBaseUrl,
    occPrefix: '',
}
endpoints: {
    product: '',
    productReviews: ''
}
site: {
    baseSite: ''
}
```

These are too generic, and would become unclear as soon as we start adding other backends (Service Factory, Yotpo, etc.). Therefor we like to use:
```
backend: {
    occ: {
        baseUrl: '',
        prefix: '',
        site: '',
        endpoints: {
            product: '',
            productReviews: ''
        }
    }
}
```

**Comment by Platonn** [comment]
We keep `site` where it is now. The rest of proposed config format is ok.

**Comment by Platonn** [comment]
QA steps:
1. configure custom (fake) `baseUrl`, occ `prefix` and `endpoints` in `backend.occ` config property and verify that HTTP calls are made to custom url
2. configure baseUrl in meta tag in `index.html` and verify that HTTP calls are made custom base url
3. Configure valid baseUrl and travel quickly through whole application (because almost every feature makes calls to OCC) - manual smoke test.

**Comment by KateChuen** [comment]
- [X] configure custom (fake) baseUrl, occ prefix and endpoints in backend.occ config property and verify that HTTP calls are made to custom url
Changed it to this: 

> backend: {
       occ: {
         baseUrl: 'https://hybris.com:9001',
       },

And confirmed that the calls were being made to the custom url.
<img width="1432" alt="occEndpoint" src="https://user-images.githubusercontent.com/45409515/55830649-5ca47780-5adf-11e9-8aba-937d8a40391c.png">


- [X] configure baseUrl in meta tag in index.html and verify that HTTP calls are made custom base url
Changed this:
<img width="584" alt="metaIndexChange" src="https://user-images.githubusercontent.com/45409515/55830691-7c3ba000-5adf-11e9-8593-4d4532427b1e.png">

And confirmed that the calls were being made to the custom url.
<img width="1430" alt="metaIndex" src="https://user-images.githubusercontent.com/45409515/55830686-7940af80-5adf-11e9-9005-8a783139460d.png">

- [ ] Configure valid baseUrl and travel quickly through whole application (because almost every feature makes calls to OCC) - manual smoke test.
Configured this: 
> backend: {
       occ: {
         baseUrl: 'https://dev-com-19.accdemo.b2c.ydev.hybris.com:9002',
       },

Went quickly through the application. Was not able to perform a complete smoke test though, because the login screen is missing the login form on dev19 (was like this even before those changes. Gil was troubleshooting this issue but it hasn't been solved yet). 

We only have dev19 for making changes for QAing.

**Comment by keustma** [comment]
I just saw the Wiki page is not up-to-date with this change. I wanted to create a PR for this, but apparently that is not possible for the Wiki pages. Could you please update the Wiki page to reflect this config change ?

https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Setup-and-Installation
