### ISSUE TITLE
Configurable OCC endpoints for site-context adapters

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1795]
Add configurable OCC endpoints for site-context adapters.

See #1790

**Comment by LTiger14** [comment]
### QA Steps:

- Go to homepage, languages and currencies should be loaded
- Login or create user
- Add product to cart and go to checkout
- In the shipping address form make sure the countries are loaded
- Select `Canada`
- Make sure the regions are loaded
- Select `United States`
- Make sure the correct regions are loaded

**Comment by giancorderoortiz** [comment]
Tested with the following endpoints: 
languages: 'espanol',
currencies: 'peso',
countries: 'canada'

Language and currency dropdowns are handled correctly. i.e, not shown because endpoint doesn't exist. 

In the case of countries, upon checkout attempt, I'm unable to add a new address because country dropdown list doesn't appear. It appears to be correct. 

In above cases, I do see the correct error message in dev-tools.

**Comment by giancorderoortiz** [comment]
Currency: 
![currency](https://user-images.githubusercontent.com/46171897/62656423-231b3600-b932-11e9-9abe-c5372525a557.png)

Language and Currency:
![lang_and_currency](https://user-images.githubusercontent.com/46171897/62656424-231b3600-b932-11e9-8b0d-6a993f4853c4.png)

New Address
![countries_add_address](https://user-images.githubusercontent.com/46171897/62656421-231b3600-b932-11e9-8ae1-c8050068080e.png)
