### ISSUE TITLE
[Master] Fetch baseSites configuration from backend

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#1810]
Use baseSites endpoint `/rest/v2/basesites?fields=FULL` to fetch configuration from backend.

Fallback mechanism using configuration should also be considered (to support older backends).

**Comment by Xymmer** [comment]
Stan to refine and make small tickets.

**Comment by tobi-or-not-tobi** [comment]
We agreed on using the existing `/basesites` endpoint, which was introduced in 1905. While the payload might be too heavy and we need to do some additional  filtering client-side, the benefit is that we're not blocked by any backend work. Moreover, we have SSR with state-transfer, which means that the initial load is not blocked with a first backend call.

**Comment by Platonn** [comment]
## QA steps:
### Prerequisites:
1 . set occ base url in meta tag (`index.html`) to dev-com17
2. add to local `hosts` file:
```
127.0.0.1 multi-store.com apparel.com apparel-de.store.com apparel.de.store.com apparel-uk.store.com apparel.uk.store.com multi-store.com fail.store.com
```

### Browser
3. Run `yarn start --disable-host-check` 
4. Open URLs and play with them:
- http://multi-store.com:4200/electronics-spa
- http://multi-store.com:4200/electronics
- http://apparel.de.store.com:4200/
- http://apparel.uk.store.com:4200/

a) Verify that those use different (dynamic) base sites, url encoding attributes, languages, and currencies (including defaults).

b) Verify that those fail due to no matching url pattern for any base site:
  - http://fail.store.com:4200/
  - http://multi-store.com:4200/

### SSR
5. Run SSR
``` 
yarn build:core:lib
yarn build
yarn build:ssr
yarn start
```
6. Verify the (4) again but in SSR

**Comment by Pucek9** [comment]
Server qa done
