### ISSUE TITLE
Update Email: Implement Authentication process state feedback 

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1921]
In order to provide robustness an adequate user experience, the authentication needs to provide feedback about the process.

# Add login process feedback

We need to leverage/reuse the generic process state management feature.
For info, see "Process State Management" in GH-1580

# Add "update email flow" functions to the facade
What we can do is then provide facade functions that will "orchestrate" the update email flow:

We would add to the facade these functions:

updateEmailFlow() {} // Truggers the update email + trigger the authentication on success.
getupdateEmailFlowSuccess() // Combines the update email + authentication streams
getupdateEmailFlowError() // Combines the update email + authentication streams
getupdateEmailFlowLoading() // Combines the update email + authentication streams

# Adjust the UI component.

Next we need to tweak to UI to use the update email flow instead and leave the authentication trigger to the email flow.

**Comment by znikola** [comment]
This is an example how we could implement the combining part using `combineLatest` rxjs operator: https://stackblitz.com/edit/combine-latest-example

**Comment by bgambocjaviniar** [comment]
PR: GH-1927

**Comment by bgambocjaviniar** [comment]
Yesterday, we discussed that the ticket is done, but somewhat blocked. There is a problem with the occ calls that is happening which throws a global error message that says the user is anonymous. This happens because that call is called before the new token was loaded, therefore failing.

In conclusion, we discussed 4 possible solutions:
1) Leave it as-is with the error message.
2) Hide the error message + create a followup ticket to find a cleaner solution.
3) Find a cleaner solution before we release: Refactor the “CartData” implementation that seems to conflict with the email change.
4) Find a cleaner solution before we release: Investigate further to find a different solution than the CartData refactor.
