### ISSUE TITLE
Consignment tracking phase 1

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2024]
This is a placeholder ticket for KungFu Panda's work on consignment tracking.
link to PR to come.

**Comment by KevinSu89** [comment]
The code is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/compare/feature/PANDA-3071

**Comment by Seven7hang** [comment]
As you know, we are implementing the consignment tracking feature based on existing code of order details page. Regarding this working model, we have 4 concerns:
1. Unit test: our changes will introduce impacts on the existing unit test
2. Maintainability: as we introduced changes on the existing code, will it bring a bit more difficulties for troubleshooting in the future?
3. Threats modeling: I suppose you've already done a threats modeling for existing feature, then we introduced our changes, need we do another one?
4. Ngrx: As we aligned before, we needn't to consider the ngrx implementation for now. However, we are coding based on existing implementation, need we also complete the ngrx things?

Another proposal is you provide enough extensibility, e.g. outlet, so that we can define our component and introduce our or override your page fragment. 
The CONS: more than one places are handling a same page, and it may make customer confused when they want to introduce their functionalities.

**Comment by KevinSu89** [comment]
The related jira item is https://jira.hybris.com/browse/PANDA-3071

**Comment by KevinSu89** [comment]
We have done a POC of this feature so close this issue now. I will create another issue for implementation.

**Comment by KevinSu89** [comment]
Close this issue since POC is done. I will create another issue for release
