### ISSUE TITLE
Help component in checkout requires styling on mobile version

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2089]
Related to #2001, extensible-checkout epic. Header and footer needs styling:
![image](https://user-images.githubusercontent.com/788092/56413253-273e1d80-6287-11e9-9307-0c41b47f6e54.png)
![image (1)](https://user-images.githubusercontent.com/788092/56413249-23120000-6287-11e9-9819-857d54c68477.png)

## Environment Details

- Spartacus:  `feature/extensible-checkout-FR2`
- Browser: chrome, mobile devtools

## Steps to Reproduce
Go thru the checkout process on mobile version.

## Observed Results
Header and footer of the page looks ugly overlaps (header) or no space (footer) - needs ux/styling.

## Expected Results
No overlaping proper spacing should be in header and footer.

## Repository Used
https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/feature/extensible-checkout-FR2

**Comment by Matejk00** [comment]
Just to sum up, these bugs exists on /checkout route which will be deleted in final version of FR2, so we don't need to fix that.

In this PR covered was mobile styling for specified checkout step routes. I moved SideContent slot to be displayed always at the bottom instead of right side on mobile screens.
