### ISSUE TITLE
SPIKE: Anonymous consent

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2124]
Now that the APIs support anonymous consent tracking
https://jira.hybris.com/browse/RAY-214
https://jira.hybris.com/browse/RAY-222

Spike what we have to do in Spartacus to request anonymous consent and then remember it for the anonymous session. Need to try out the APIs first.

(also see epic ticket #1323)

See docs here for how it's done in backend: https://help.hybris.com/1811/hcd/a9f387f70d484c19971aca001dc71bc5.html

Screenshot: https://wiki.hybris.com/display/spar/Accelerator+Pages-Templates+Reference#AcceleratorPages-TemplatesReference-AnonymousConsentfortrackingactivity

There's also cookie consent, need to know if they are both needed or just the one.

Need to discuss also with security to make sure it's done properly.

**Comment by pg-sap** [comment]
This feature mirrors the anonymous consent support in Accelerator, except that a HTTP header is used to synchronize settings with the back-end (instead of cookies).

Spartacus has to store consents for anonymous users in local storage (or the like). Then, exchange that information with the back-end via HTTP header `X-Anonymous-Consents` with URL-encoded JSON as the header value.

There is no separate REST API - a new HTTP interceptor has to be implemented in Spartacus to handle the `X-Anonymous-Consents` header.

1. Send URL-encoded JSON with consents in the request header `X-Anonymous-Consents`.
2. Read the `X-Anonymous-Consents` response header for your JSON processed by the back-end.
3. Update anonymous user's consents in local storage.

Please note some special cases, like:

- In case of a missing request header, the back-end will respond with initial JSON
- Consent templates might change in the meantime, hence the need to check the response header for an updated JSON
- Applies to anonymous users only

**Comment by Xymmer** [comment]
we'll do this after 1.0 launch

**Comment by znikola** [comment]
Sample data PR: https://github.tools.sap/cx-commerce/c3po-legacy-spartacussampledataaddon/pull/7
