### ISSUE TITLE
customizable&better ui navigation / drop ngBootsrap dropdown

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2135]
Navigation ui component uses `ngbDropdownToggle` from Ng-bootstrap for the dropdown on links with children. This ticket should:

- Remove the use of `ngbDropdownToggle`
- Implement custom logic and styling mimicking `ngbDropdownToggle`
- Not all the feature from the ng-bootstrap components are needed but the Spartacus behaviour should be the same

Don't forget to adjust the unit test and remove the BootstrapModule import from this component's module.

**Comment by mszczepaniak** [comment]
There is not only a problem about the `ngbDropdownToggle`, but also all of the other parts of the angular bootstrap dropdown :
- ngbDropdown
- ngbDropdownMenu
Essentialy if we remove the BoostrapModule import from the component's module, we need to replace both above bootstrap directives as well.
I have made a POC with different opensource solutions:
https://github.com/topaxi/angular-dropdown#readme
https://github.com/karanhudia/angular-dropdown-component

Whoever takes over this ticket, would need to choose among them and restyle accordingly to our bootstrap existing one.

**Comment by mirkosoft** [comment]
this issue will be covered with changes in the above @tobi-or-not-tobi 's PR. So we can close it as soon as the PR is merged.

**Comment by mirkosoft** [comment]
currently working on test for this; in the meantime @tobi-or-not-tobi will push more to this PR

**Comment by mirkosoft** [comment]
Here, basically there is a need to fix all the unit tests (storefrontlib) and check e2e. Just switch to the branch and fix them. I didn't manage to fix any of theese before my leave.

**Comment by Xymmer** [comment]
This was started in Asterix, finished by Tobias, and we're moving this to Gladiators for review.

**Comment by tobi-or-not-tobi** [comment]
QA:
- confirm that ng-bootstrap is no longer used in navigation (either in the DOM or in code)
- navigation in desktop opens on hover (before it was on click)
- Implementation is aligned with proposed UX and design
- A "Shop all" link is added to the child panel, in case the navigation header has a URL and childs
- The navigation on mobile uses slides
- footer navigation UI in desktop mode has aligned with design
- navigation links in digital camera are aligned in a column rather than a row
- fly-out navigation on desktop have a small border so that they appear nicely on white backgrounds
- CMS data has changed so that the navigation is more condensed
- header navigations are aligned to the left (no longer spread over the header)

**Comment by KateChuen** [comment]
Tested on dev2:

- [x] confirm` that ng-bootstrap is no longer used in navigation (either in the DOM or in code)
Didn't see traces of ng-bootstrap for navigation

- [X] navigation in desktop opens on hover (before it was on click)
Indeed, navigation in desktop opens on hover now. 

- [X] Implementation is aligned with proposed UX and design
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2909

- [X] A "Shop all" link is added to the child panel, in case the navigation header has a URL and childs
<img width="1031" alt="navLinksDigitalCam" src="https://user-images.githubusercontent.com/45409515/58960869-06b61e00-8776-11e9-9a65-626d78c1be9c.png">

- [X] The navigation on mobile uses slides
<img width="507" alt="mobileSlides" src="https://user-images.githubusercontent.com/45409515/58962454-30247900-8779-11e9-80cf-3de40b9dbfc4.png">

- [X] footer navigation UI in desktop mode has aligned with design
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2852

- [X] navigation links in digital camera are aligned in a column rather than a row
<img width="1031" alt="navLinksDigitalCam" src="https://user-images.githubusercontent.com/45409515/58960869-06b61e00-8776-11e9-9a65-626d78c1be9c.png">

- [X] fly-out navigation on desktop have a small border so that they appear nicely on white backgrounds

- [X] CMS data has changed so that the navigation is more condensed

- [X] header navigations are aligned to the left (no longer spread over the header)
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2907
