### ISSUE TITLE
Grid / List view icons transposed

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2244]
Description:  On all the catalog pages, the icons for list and grid are transposed. When the system is displaying list view, the grid icon should appear in the upper right corner. If the system is displaying the grid view, the icon in the upper right corner should be the list view icon.

How to duplicate: Visit any search result or subcategory listing page

![SNAG-0015](https://user-images.githubusercontent.com/44620139/56984037-188f1a80-6b53-11e9-9a16-da7151c97822.png)

**Comment by RadhepS** [comment]
PR: GH-2495

**Comment by LTiger14** [comment]
QA:

Something might have happened with the icon component but this isn't working anymore. As shown by these screenshots.

![Screen Shot 2019-05-20 at 9 42 07 AM](https://user-images.githubusercontent.com/10605724/58026186-e6cefb00-7ae3-11e9-9efe-a4b99e92005b.png)
![Screen Shot 2019-05-20 at 9 42 13 AM](https://user-images.githubusercontent.com/10605724/58026190-e9315500-7ae3-11e9-8b25-fd22c9e3fe7b.png)

It seems that the icon now appends classes instead of replacing them.

**Comment by RadhepS** [comment]
PR: GH-2583

**Comment by bgambocjaviniar** [comment]
Passing the hotfix, but needs to be followed up with Tobias on the cx-icon component
