### ISSUE TITLE
Different line height when configured SVG icons

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2328]
When configured SVG icons, the line height is bigger which affects the layout (i.e. look of search box).
Compare CSS (standard) and SVG (configured):
- CSS:
![obraz](https://user-images.githubusercontent.com/4001059/57301704-ed1fa900-70d9-11e9-93dc-7ace7ea6fad9.png)

- SVG:
![obraz](https://user-images.githubusercontent.com/4001059/57302180-e6ddfc80-70da-11e9-9e2b-859c5d40259e.png)

**Comment by developpeurweb** [comment]
@tobi-or-not-tobi and @LTiger14 can you pls weight into this issue. You can pull this branch directly and test it out `feature/GH-2328`, is already setup with the svg sprite and app configuration needed.

**Basically I can't reach a one-size-fits-all solution.**

To get rid of the **_line-height issue_** should be enough to set `cx-icon svg {display:block;}` as per screenshot but then we get an unwanted effect for the lang/currency carets and the product stars, which also won't pickup the color since I think this svg setup breaks the `ng-bootstrap` functionality.

![Screen Shot 2019-05-14 at 11 39 25 AM](https://user-images.githubusercontent.com/15113219/57711634-10e47100-763d-11e9-82ac-f8bafd977d77.png)

**_Carets_** can be repositioned individually if adding `cx-site-context-selector cx-icon {position: absolute;}`

![Screen Shot 2019-05-14 at 11 44 09 AM](https://user-images.githubusercontent.com/15113219/57711962-be578480-763d-11e9-8419-056fc1ba297b.png)

**_Product stars_** rating can also be fixed individually as per screenshot below, but as state, haven't found a a one-size-fits-all solution. 

![Screen Shot 2019-05-14 at 11 50 04 AM](https://user-images.githubusercontent.com/15113219/57712612-e2679580-763e-11e9-9b24-c7b40c7599b3.png)

Also in all cases, sizing has to be done individually (ex. While Search and Cart are OK, carets are way too big with the custom icon due to fixed sizing in `_icons.scss`).

**Any ideas how to proceed on this one?**

**Comment by developpeurweb** [comment]
**For the record:** Adjustments done in this ticket doesn't fix the star-rating feature based on `ng-bootstrap` that will to be tackled separately in GH-2469

**Comment by Xymmer** [comment]
looks good to me
