### ISSUE TITLE
[will be solved with #2552] E2E Cypress tests randomly failing

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2365]
My first guess is localization - labels are loading asynchronously (was just hardcoded before the localization work). Some examples (smokes):
* checkout-flow -> choose delivery method: sometimes Cypress complains radio button is not visible (size 0x0)
* checkout-flow -> login link can not be found while it is obviously present.
* more to come

**Comment by Zeyber** [comment]
In checkout-flow smoke tests running cypress, no tests fail on my regular network (fast) no matter how many times I reran tests. When I throttled the network to 3G Slow on chrome's dev console, all tests failed. When I set the default timeout for cypress commands to a much higher number (60 seconds) then all tests past again. Just wondering if the issues may have been occurring from network issues?

**Comment by Zeyber** [comment]
I've ran quite a bit of tests on headless now and heres what I've come across:
- Changing timeout from anything down to 4 seconds on my pc passes all e2e tests (checkout-flow failed just once)
- 3 seconds, only checkout flow fails but more frequently
- 2 seconds and lower, other tests start to fail
- Checkout fails are due to timeout error (async changes have not been loaded before timeout)
- Suggesting increasing timeout limit to allow for successful e2e testing on slow connections

**Comment by Zeyber** [comment]
cypress.json
`
...
"defaultCommandTimeout": 30000,
...
"requestTimeout": 30000,
...
`
Set timeout to 30 seconds to allow ample time for components to render.

**Comment by kacperknapik** [comment]
@dunqan is that the one you already fixed?

**Comment by Pucek9** [comment]
Will be done in #2552

**Comment by mirkosoft** [comment]
closing as @2552 is done and test do not fail
