### ISSUE TITLE
Manual test for extensible checkout

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2479]
Go through different checkout flows to find if we introduced some regressions, bugs into new checkout feature. Test for new users, existing addresses, aborting checkout, removing an address, payment details during checkout and any other complicated flows we might forget.

**Comment by Matejk00** [comment]
1. Not logged in user is able to reach directly checkout step pages: f.e. /checkout/payment-details
![1](https://user-images.githubusercontent.com/6958810/57909872-37481d80-7884-11e9-8260-5a90c79984bb.png)

2. When unlogged user add some product to the cart and then click procced to checkout is redirected to first checkout step, but when he will fill shipping address form is not able to go forward (maybe because userId param is missing?)
3. On shipping address step "Back to cart" button is not working
4. (Not strictly connected with FR2 work). When user wants to add new shipping address, not the first one, just another and after he fill the form and click continue he still see unfilled form for a moment then is redirected to the next step. Shouldn't we hide a form during adding new address process is in background?
5. When payment step is not filled yet, user is able to go directly to /checkout/review-order using browser bar.
6. (Back to topic) Should we handle next checkout progress steps to be active if user filled them previously and back to do some changes in previous steps?

**Comment by Matejk00** [comment]
Issue created for must-have-fixed bugs. #2534
