### ISSUE TITLE
Remove userId arguments in User Facade - Address functions

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2512]
See master ticker GH-1092
Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.

* loadAddresses(userId: string): void {
* addUserAddress(userId: string, address: Address): void {
* setAddressAsDefault(userId: string, addressId: string): void {
* updateUserAddress(userId: string, addressId: string, address: Address): void {
* deleteUserAddress(userId: string, addressId: string): void {

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by bgambocjaviniar** [comment]
PR: GH-2718

**Comment by bgambocjaviniar** [comment]
Test:

- Make so there's no trace of userId in

1. loadOrderDetails(userId: string, orderCode: string): void {
2. getOrderHistoryList( userId: string, pageSize: number ): Observable {
3. loadOrderList( userId: string, pageSize: number, currentPage?: number, sort?: string ): void {

- Make sure address is still functional as it was before in terms of creating in checkout, and in address book

**Comment by KateChuen** [comment]
Tested on dev2.
- Verified that "current" is now used instead of email add.
Get Addresses
<img width="1438" alt="currentGetAdd" src="https://user-images.githubusercontent.com/45409515/58571336-850b4100-8207-11e9-97cd-987505459b64.png">
Add New Address
<img width="1435" alt="currentCreateAdd" src="https://user-images.githubusercontent.com/45409515/58571333-8472aa80-8207-11e9-8f61-1313d4f74131.png">
Set default
<img width="1439" alt="currentSetDefaultAdd" src="https://user-images.githubusercontent.com/45409515/58571338-850b4100-8207-11e9-9731-36c78b05927a.png">
Edit Address
<img width="1437" alt="currentEditAdd" src="https://user-images.githubusercontent.com/45409515/58571335-8472aa80-8207-11e9-8988-94ea67f390bc.png">
Delete Address
<img width="1438" alt="currentDeleteAdd" src="https://user-images.githubusercontent.com/45409515/58571334-8472aa80-8207-11e9-83f5-6aff17e22795.png">

- Verified that address book works as before (load, add, delete, edit, set as default, checkout, logout)
