### ISSUE TITLE
[wait for other beautacus tickets] Update Beautacus sampledata

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#2551]
The beautacus backend at https://api.cehm0u1-sccdemoin1-d3-public.model-t.myhybris.cloud/ is outdated which causes the frontend to be missing certain features.

This ticket is to update beauty sample data with the latest updates from spacceleratorsamplesaddon.

**Comment by WeizhengSap** [comment]
PR is here: https://stash.hybris.com/projects/C3PO/repos/beautystore/pull-requests/1/overview

**Comment by WeizhengSap** [comment]
To QA and code reviewer:
You have to clone the "beautystore" into source folder.
You need to add `<extension name="beautystore"/>` into `localextension.xml`. Then rebuild and initialize the system.
Then, in `app.module.ts`, 
```
siteContext: {
        urlEncodingParameters: ['BASE_SITE', 'LANGUAGE', 'CURRENCY'],
        parameters: {
          BASE_SITE: {
            values: [
              'electronics-spa',
              'electronics',
              'apparel-de',
              'apparel-uk',
              'beauty',
            ],
            defaultValue: 'beauty',
            persistence: 'route',
          },
        },
      }
```
Beauty store only have "English". So, there is no "language" selector. But, it has 2 currencies, so you should be able to see the "currency" selector". Then, you can do a smoke tests.

**Comment by KateChuen** [comment]
Started testing on dev2. Able to load the beautacus and see the currency selector. 
![beautyCurrency](https://user-images.githubusercontent.com/45409515/58710637-c5df9300-838a-11e9-8a63-db3e8e820d0d.png)

- However some issues, for eg "the best sellers" category link doesn't work.
- Cannot add product from pdp (it shows out of stock) when we can add the same product from plp.
- Cannot complete checkout since the payment is calling "localhost". Will probably need to test it on dev17. 
- So conclusion, will wait for the other beauty tickets to be done, to test this one.

**Comment by RadhepS** [comment]
Hi Kate, for this issue: "Cannot complete checkout since the payment is calling "localhost". Will probably need to test it on dev17."

I had a similar issue and it was fixed by adding `sop.post.url=https://localhost:9002/acceleratorservices/sop-mock/process` 
into my local.properties file.

**Comment by KateChuen** [comment]
Tested it on dev2. 
Can checkout indeed. But getting a 404 on OrderConfirmation page. Ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2938
