### ISSUE TITLE
Doc input for localization

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2582]
Create/update docs for last localization changes. Related to #1486

**Comment by kacperknapik** [comment]
@mirkosoft I just added this ticket to `Documentation` project, so @gladius-mtl can take a look at it :)

**Comment by gladius-mtl** [comment]
Doc input check completed. Thank you for the input! I created a draft on the wiki: https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Internationalization-%28i18n%29-%28DRAFT%29

I have also created a follow-up ticket to do a full edit and review of the input, here: GH-2827. Since I'll carry out the review in this separate ticket, I'm closing this doc input ticket and moving it to done.

Thank you very much! 😄
