### ISSUE TITLE
Use 'current' instead of the email in the occ urls - step 1.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2584]
See master ticker GH-1092

Change the authentication logic to use 'current' instead of the uid in the OCC

The expected results are:
- In the app state (auth> userToken> token> userId) and the local storage 'current' is saved in the userId field.
- the cart interaction requests use 'current' instead of the email. (other OCC calls now use 'current', but the cart is the biggest single piece impacted by the change in this ticket)
- the e2e tests are updated to use current instead of the user uid.

**Comment by plabadie** [comment]
PR #2601

**Comment by plabadie** [comment]
For tests:

Tests are all about regression for this ticket.  The main change is under the hood: Many occ calls now use 'current' in the occ endpoint urls while before the user email was used.  Performing checkout and making sure that occ calls don't use emails is a good smoke test.
See ticket description for key points to validate.

**Comment by Xymmer** [comment]
Nik says this ticket also resolves #690, how to test that?

**Comment by KateChuen** [comment]
- Verified that occ calls on cart page and during checkout are using "current" instead of the "email".
- Add to cart, update cart qty, remove from cart:
![currentAddCart](https://user-images.githubusercontent.com/45409515/58433515-ac3a0500-8085-11e9-94f7-61ba483e08dd.png)
![currentupdateQty](https://user-images.githubusercontent.com/45409515/58433516-acd29b80-8085-11e9-9582-44b3b04252bc.png)
![deleteItemCart](https://user-images.githubusercontent.com/45409515/58433517-acd29b80-8085-11e9-86dd-7a3eb9b5da86.png)

- checkout steps:
![currentShippingAdd](https://user-images.githubusercontent.com/45409515/58433543-c5db4c80-8085-11e9-886a-1b9a2efed364.png)
![currentDeliveryMode](https://user-images.githubusercontent.com/45409515/58433539-c542b600-8085-11e9-9df1-52dba983aea7.png)
![currentPaymentDetails](https://user-images.githubusercontent.com/45409515/58433540-c542b600-8085-11e9-9626-400737921747.png)
![currentReviewOrder](https://user-images.githubusercontent.com/45409515/58433542-c5db4c80-8085-11e9-9562-2c87c8329e09.png)
![currentPlaceOrder](https://user-images.githubusercontent.com/45409515/58433541-c5db4c80-8085-11e9-9850-512cc6798133.png)

- For MyAccount, mostly still using "email" but this will be tackled in other tickets of the epic. Only Order History is already using current.
![currentGetOrders](https://user-images.githubusercontent.com/45409515/58433564-dbe90d00-8085-11e9-9122-87a253f6e5d6.png)
![currentGetAnOrder](https://user-images.githubusercontent.com/45409515/58433563-db507680-8085-11e9-9315-d14be57a40ea.png)
