### ISSUE TITLE
Add config 'enabled' in personalization

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#2651]
personalization can be enabled in backend. In our current SPA, it always supports `personalization` (adding personalization request headers) even it is disabled in backend.

So, only when `enabled=true`, SPA supports personalization. If `enabled=false`, the personalization related data saved in local storage should be cleared.

**Comment by WeizhengSap** [comment]
Please check https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1990 and https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2316 of how to enable personalization.

**Comment by plabadie** [comment]
PR #2715

**Comment by plabadie** [comment]
To test:

After personalization is enabled in the backend, observe that:
* personalization header are not present in requests and are not present in the browser's local storage since personalization is disabled by default in Spartacus.
* Enable personalization and see that there are 2 personalization headers in the requests as well as personalization entries in local storage.  Personalization is enabled with this in app.module:
```
    StorefrontModule.withConfig({
      personalization: {
        enabled: true,
      },
```
* Disable personalization and and validate that the headers are no longer sent in urls and also that the local storage personalization info is deleted.

**Comment by Xymmer** [comment]
Doc input provided in https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/50
