### ISSUE TITLE
Media glitches

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2692]
There are different issues with media currently:
- we like to change everything to the new storefront lib layout  (#2662), there's still a hardcoded unknown product image in the old lib layout
- the unknown product image should not be part of the JS 
bundle;
- the unknown product image is used as any general unknown image
- the unknown product image is shown initially while the product images are being loaded
- the landing page is full of media loaders when the page is loaded. This is stupid and ugly too.
- customer should be able to customise the unknown image easily. 
- the spinner loads forever; this takes computing power, the animation should be paused.
- switching product detail page is causing runtime errors because of media

**Comment by tobi-or-not-tobi** [comment]
QA steps: 
confirm all steps from the ticket description

**Comment by KateChuen** [comment]
- [ ] we like to change everything to the new storefront lib layout (#2662), there's still a hardcoded unknown product image in the old lib layout
-> How to verify this?

- [ ] the unknown product image should not be part of the JS bundle;
-> How to verify this?

- [ ] the unknown product image is used as any general unknown image
For products that don't have an image, then the "image coming soon" is displayed. Is that the unknown product image?

- [ ] the unknown product image is shown initially while the product images are being loaded
The product image is loaded fast, didn't have time to see the unknown product image

- [X] the landing page is full of media loaders when the page is loaded. This is stupid and ugly too.
No media loader when page is being loaded.

- [ ] customer should be able to customise the unknown image easily.
Have to know which image it is and where to change it

- [ ] the spinner loads forever; this takes computing power, the animation should be paused.
The spinner doesn't load forever now. It's fast.

- [X] switching product detail page is causing runtime errors because of media
Doesn't cause any error now

**Comment by tobi-or-not-tobi** [comment]
> we like to change everything to the new storefront lib layout (#2662), there's still a hardcoded unknown product image in the old lib layout
-> How to verify this?

The "image coming soon" should be driven by CSS, so you should be able to verify in chrome desktop tools that it is part of a CSS rule. Previously it was part of the JS bundle. 

> the unknown product image should not be part of the JS bundle;
-> How to verify this?

See previous. 

> For products that don't have an image, then the "image coming soon" is displayed. Is that the unknown product image?

Correct

> customer should be able to customise the unknown image easily.
Have to know which image it is and where to change it

It's CSS, you can override the `%cx-media-missing` placeholder selector in sass, or change the `cx-media.is-missing` class.

**Comment by KateChuen** [comment]
@LTiger14 can you please verify the "customize" step please? Thanks.

**Comment by LTiger14** [comment]
I was able to customize the image by overriding `%cx-media-missing`
![Screen Shot 2019-06-03 at 3 15 01 PM](https://user-images.githubusercontent.com/10605724/58828004-65628700-8612-11e9-867b-955c52cf0200.png)
