### ISSUE TITLE
Remove userId arguments in User Facade - Load User Details

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2763]
See master ticker GH-1092

Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.

*   load(userId: string): void {

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by plabadie** [comment]
PR #2765

**Comment by plabadie** [comment]
For tests:

This requires regression testing on the user details load.
After you authenticate:
- you can look in the redux dev tools and see the user details are present.
- you can see your name/last name in the greeting section in the header
- spot check the update user details feature
- Test that the get user details request uses current as the username.

**Comment by KateChuen** [comment]
Tested on dev17.
- Verified that after authentication, we see the "get user call" is using current. 
- We see the first name and last name in the header
![currentGetUser](https://user-images.githubusercontent.com/45409515/58717832-25916a80-839a-11e9-9fa5-49e67384e9bf.png)

- And we see the user details in the response
![getUserResp](https://user-images.githubusercontent.com/45409515/58717847-2aeeb500-839a-11e9-8a07-1b5357bd00cc.png)

- Update user details still works as before
![updateUserDetails](https://user-images.githubusercontent.com/45409515/58717890-435ecf80-839a-11e9-8d70-1034107a9126.png)

- No testing with Redux since it's not possible on a dev server.
