### ISSUE TITLE
[not a bug?] Regions always returned in english

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2768]
Sending requests for regions with different languages always returns regions in English.

@Xymmer could you check it in backend tickets?

**Comment by Xymmer** [comment]
The ticket that fixed this was C3PO-1507
it is working, but the backend has to have translations, otherwise English is returned

in this exampe, i did a get of canadian provinces in German
https://dev-com-19.accdemo.b2c.ydev.hybris.com:9002/rest/v2/electronics/countries/CA/regions?lang=de&curr=USD

we don't have Alberta in German so i added '[de]' in front
![image](https://user-images.githubusercontent.com/4998145/58642525-8e5de180-82cb-11e9-83c7-4314fd2ce691.png)

**Comment by marlass** [comment]
I checked US states on dev-com17. That might have been the issue with missing translations.
Unfortunately, I can't check your example on dev 19, because the server is down. Will check later.

**Comment by marlass** [comment]
The functionality works correctly. Translations are missing.
