### ISSUE TITLE
Replace "Cart total $###" with cart # and remove cart # from title

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2785]
Shopping cart shows: 
![image](https://user-images.githubusercontent.com/4998145/58656153-c411c300-82e9-11e9-849f-f9553b35bf59.png)
----
1. Replace this with
Cart #[cart number]
2. If the user's cart is empty, or he has no cart, the "cart #..." line should not be displayed.

3. For the header title, replace 
"Your Shopping Cart (####)"
with
"Shopping Cart"

**Comment by bgambocjaviniar** [comment]
@Xymmer Shouldn't this be done in the b2c-addon? Because it shouldn't only be a fix for spa. Can you create a ticket for c3po please

**Comment by bgambocjaviniar** [comment]
Other than that backend 'issue', shouldn't we follow the wireframes? Another point to this is the cart # because I don't think the user needs to know the cart # before purchasing the item. I'm guessing this unique id for cart is going to be used for the order confirmation too.
---> Might be a bug or a feature, but the cart # at the beginning and after purchasing it is different by 1. For example, at the cart page it would be 0001, and in the confirmation after checking out, it would be 0002.

**Comment by KateChuen** [comment]
Tested on dev2. 

- [x] Replace this with Cart #[cart number]
![Screen Shot 2019-06-17 at 1 14 50 PM](https://user-images.githubusercontent.com/45409515/59624255-441a9400-9104-11e9-88a6-3d7e9749c74f.png)

- [x] If the user's cart is empty, or he has no cart, the "cart #..." line should not be displayed.
![Screen Shot 2019-06-17 at 1 16 48 PM](https://user-images.githubusercontent.com/45409515/59624250-40870d00-9104-11e9-9b59-3ded918e0f78.png)

- [x] For the header title, replace "Your Shopping Cart (####)" with "Shopping Cart"
It says "Your Shopping Cart" and Bill says it's ok.
