### ISSUE TITLE
[release as minor with feature flag] Change registration flow (redirect to login page after success)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2799]
Register with an email that already exists with correct password, you are logged in
if you use incorrect password, it says "Bad credentials. Please login again."

this is weird, shouldn't it just give an error?

**Comment by Matejk00** [comment]
I made a fix for this, right now if user will try to register account using email which exists but with wrong password he will get just an error.

**Comment by giancorderoortiz** [comment]
Behavior described in ticket continues to appear in dev-com19.
This whole handling is wrong. 
Should be:
1. If user attempts to register with an already used address, he/she should get an error (even a generic one). It musn't login the user. It should block the user at this point until he/she provides another email address. 

2. Entering wrong password for registration is not a valid concept. 
Acceptable cases to handle if unique email is provided are:
2.a. A password that satisfies complexity rules.  -> Then register user . Else trigger error. 
2.b. Password AND confirm password fields match exactly. -> Then register user. Else trigger error. 
2.c. Empty password -> Trigger error.

**Comment by giancorderoortiz** [comment]
e2e ticket #2443 reflects his behaviour. Further discussion needed.

**Comment by kacperknapik** [comment]
I checked the code and our requests and the problem here is that the backend is responding always the same (for new registration and for the same email, sadly). We can't really tell if the user is new or not. There are some dirty hacky solutions, but I'm not a big fan of this kind of approach.

TODO:
- backend (`../../users/` endpoint) should guard the registration in the way that if you try to register with a fresh, new email, you should get the user details (successful registration) and if you try with the same email, it should return an error
- frontend should show error (from the previous point) and stop the registration/login process
- (optional) create a new endpoint (eg. `../../users/is-registered/`) which would return true/false value for any passed userId - after this check we would simply show an error or go with the registration flow

**Comment by pg-sap** [comment]
The back-end is set up to **not** reveal if any particular e-mail address is already registered. This behavior has been introduced in 1905 for security / privacy reasons.

**Comment by FelixOliverLange** [comment]
well not leaking which user has created an account does make sense in my opinion.  A possible approach might be to query the authorization endpoint upfront and see rather the authentication was successful. If so, logout and redirect to the login page. Either way, what happens when registering with an existent email but wrong password? The registration endpoint should raise an error then, as far as i'm concerned. After all, the email cannot / should not be used twice.

**Comment by pg-sap** [comment]
When the e-mail address is already in use, the server discards the registration requests silently.

On 9 Jul 2019, at 16:05, Felix Lange <notifications@github.com<mailto:notifications@github.com>> wrote:


well not leaking which user has created an account does make sense in my opinion. A possible approach might be to query the authorization endpoint upfront and see rather the authentication was successful. If so, logout and redirect to the login page. Either way, what happens when registering with an existent email but wrong password? The registration endpoint should raise an error then, as far as i'm concerned. After all, the email cannot / should not be used twice.

**Comment by pg-sap** [comment]
When the e-mail address is already in use, the server discards the registration requests silently.

**Comment by kacperknapik** [comment]
So just to wrap up, we discussed this problem with @plabadie @giancorderoortiz and @gladius-mtl and the current, short-term solution is to redirect the user straight to login form/page after the registration form was submitted (+ info, eg. 'you just registered, please login'). The future solution (ideally some email with link to login page) will be further discussed.

**Comment by kacperknapik** [comment]
QA steps:
- open the app
- go to register form
- register a completely fresh user
- (at this point you should be redirected to login page and have global message with success info)
- log out
- go to register form again
- register THE SAME user as above
- (you also should be redirected to login page with the same global message)

NOTE:
- you should not be redirected to homepage as a logged-in user

**Comment by KateChuen** [comment]
Tested it quickly on my local. Will wait until it's available on a server to test there. 
But for now, registering the same existing user (with both the correct and wrong passwords) give the same message on the login page. 

<img width="1434" alt="Screen Shot 2019-07-30 at 4 05 17 PM" src="https://user-images.githubusercontent.com/45409515/62161713-cfcb3700-b2e4-11e9-8824-f3f532aac726.png">

**Comment by giancorderoortiz** [comment]
Expanding on Kate's comments:
1. When attempting to re-register a user, after redirection to login page the wrong error message says "Please login with your new credentials", which is false. There are no new credentials. 

Here, a decision is needed as follows:
1.a. Show nothing and redirect to login page.  
1.b. Show error message stating email is already in use and remain in registration page. 
1.c. Show error message and redirect to login page. 

2. Don't understand the REST POST call /rest/v2/electronics-spa/users/?lang=en&curr=USD after redirection. It contains the user data of the previous registration attempt.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-07-31 at 3 15 45 PM](https://user-images.githubusercontent.com/46171897/62240970-2d738800-b3a6-11e9-9869-f2aae26554a7.png)

**Comment by Xymmer** [comment]
This fix didn't make it into 1.0.2 but we want to adhere to our no-breaking change policy.

1. This feature should use the new feature flag mechanism (talk to Stan). Devs should have to opt-in to use this.
2. Otherwise the behavior should be like 1.0 (log in automatically).

For GC's observation, when attempting to re-register a user, you get the same message, we'll fix that in the future.

**Comment by kacperknapik** [comment]
@KateChuen @giancorderoortiz guys we CANNOT show any sign of failure during this process. even the message is a sign that something is different between these two cases (registered new or existing). additionally we can't tell if the user is new or existing, so we can't show or hide this message. that's the whole idea behind this security thing. I know it's not user friendly, but that's security guys (or backend, I don't exactly know) decision and I totally agree with them.

**Comment by kacperknapik** [comment]
@giancorderoortiz will look into this POST request

**Comment by kacperknapik** [comment]
@giancorderoortiz according to our swagger backend docs, this POST request is the main registration request (see photo below). it returns response with user's data

![image](https://user-images.githubusercontent.com/22354613/62698049-7ba70d80-b9dc-11e9-9a9c-8f867f34e238.png)

**Comment by giancorderoortiz** [comment]
Further discussion needed.

**Comment by meeque** [comment]
I fear that the underlying problem lies with the registration request itself. Ideally such request would always return the same response, regardless of whether the account already existed or not. Does it do that?

**Comment by Xymmer** [comment]
@meeque: indeed this was fixed in OCC for commerce 1905 release.

**Comment by kacperknapik** [comment]
**QA steps:**

1. test old flow
- in `app.module.ts` add version `1.0` (look at the picture below)
- start the app
- go to register page
- register an account
- **you should be redirected to homepage and you should be logged in**
- log out
- go to register page again
- register an account (with the same credentials as above)
- **you should be redirected to homepage again**

2. test new flow
- change version to `1.1`
- start the app
- go to register page
- register an account
- **you should be redirected to login page with global message showing**
- log out
- go to register page again
- register an account (with the same credentials as above)
- **you should be redirected to login page again**

![image](https://user-images.githubusercontent.com/22354613/63847194-904c4500-c98d-11e9-9593-de819be06f61.png)

**Comment by Zeyber** [comment]
Confirmed as working according to the steps
