### ISSUE TITLE
Last navigation dropdown is out of the window

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2860]
In dev17, on medium size screen:

Open the `Accessories` navigation dropdown. Then the dropdown content is out of the window:

![obraz](https://user-images.githubusercontent.com/4001059/58887711-65cc5200-86e6-11e9-8f6b-be0b6ec22aa5.png)

**Comment by developpeurweb** [comment]
The original screenshot is outdated as we have moved away from `ng-bootstrap` at this point, but the issue still remains and will keep coming back if not approached on a larger scope.

There is little that can be done with CSS in this case, other than customizing the columns to stack at breaking points (as per following screenshot) but then it will also depend on the customer's data:

![Screen Shot 2019-06-13 at 12 10 42 PM](https://user-images.githubusercontent.com/15113219/59462407-ac5e3280-8df1-11e9-9d8d-2a8b37aad898.png)

If we take the **Accelerator** as a reference, there we have a dropdown menu that dynamically repositions itself depending on the viewport, but that's jQuery, we would need similar behaviour done with **TypeScript** for Spartacus. Do note that the solution in Accelerator doesn't comply with **Accessibility Guidelines**.

![Screen Shot 2019-06-13 at 3 35 09 PM](https://user-images.githubusercontent.com/15113219/59462478-cf88e200-8df1-11e9-976c-b8a83c21d49c.png)

Provided that the **Main Navigation** also must include major **Accessibility** features as commented in GH-2853, I suggest a coordinated effort focused on requirements instead of getting in a cycle of patching the navigation here and there/now and then.

cc @Xymmer

**Comment by RadhepS** [comment]
Unsure why I was assigned - removing my assignment

**Comment by KateChuen** [comment]
Tested on dev2. It fits in the window now for different viewports. 

<img width="1095" alt="Screen Shot 2019-06-25 at 1 53 55 PM" src="https://user-images.githubusercontent.com/45409515/60121530-48246280-9751-11e9-8133-25de425fbfbc.png">
<img width="979" alt="Screen Shot 2019-06-25 at 1 55 41 PM" src="https://user-images.githubusercontent.com/45409515/60121531-48246280-9751-11e9-8d96-9ee002cb01b5.png">
<img width="1424" alt="Screen Shot 2019-06-25 at 1 56 30 PM" src="https://user-images.githubusercontent.com/45409515/60121533-48bcf900-9751-11e9-8c33-97712445926e.png">


And MyAccount dropdown menu is also ok.
<img width="980" alt="Screen Shot 2019-06-25 at 1 55 49 PM" src="https://user-images.githubusercontent.com/45409515/60121553-51adca80-9751-11e9-94e2-d7b943a029d3.png">

**Comment by Zeyber** [comment]
Solution to this issue is JS heavy. If a css solution is possible, it would be cleaner.
