### ISSUE TITLE
[after ang8 switch] Re-write forbidden styles after changing from node-sass to sass

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2862]
During the upgrade to Anguar 8 we switched from `node-sass` to `sass` (which is now recommended by Angular). But in the new compiler there is forbidden so-called 'extending compound selectors', i.e. `@extend .btn.active` (see https://github.com/sass/dart-sass#behavioral-differences-from-ruby-sass).

That's why we commeted  out a few minor styling rules in `buttons.scss`. If possible, we should re-write them in other way.

For testing the old version, uncomment those styles and install locally npm package `node-sass`.

**Comment by developpeurweb** [comment]
**Important: Compound selectors may no longer be extended.** 
(We should probably mention this in the documentation)
See http://bit.ly/ExtendCompound for details.

So I've re-written the commented out rules following the example in link above and they don't seem to have an effect right now in the interface, mainly because we're barely using `aria` attributes in buttons at this moment, this will likely change once we have a clear Accessibility strategy, but it will depend on our status with Bootstrap.

**For now, it's obsolete code and I suggest removing it.**

Therefore, first commit has the rewrite and second one has the removal.

FYI: @Xymmer @mikelMHybris @LTiger14 @tobi-or-not-tobi

**Comment by developpeurweb** [comment]
**Server QA:** buttons shapes and states should remain unaffected by this change.

**Comment by KateChuen** [comment]
Tested on ccv2. Looks ok so far.
