### ISSUE TITLE
cx-star-rating styling in Safari

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#2877]
## Steps to Reproduce
Go to Safari, use local or a server like model-t (https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/)

## Observed Results

The styling for the ratings are reversed, or sometimes jumbled. As shown below.

![Screen Shot 2019-06-04 at 2 30 40 PM](https://user-images.githubusercontent.com/29099466/58904532-b8514280-86d5-11e9-872f-6ebe68be04f9.png)

![Screen Shot 2019-06-04 at 2 33 52 PM](https://user-images.githubusercontent.com/29099466/58904580-ce5f0300-86d5-11e9-9bb7-d5a61ca3b4ef.png)

## Expected Results
It should have the correct 'view' like in firefox and chrome, where it starts from left to right the ratings and not jumbled or reversed

## Additional Information
Other implementation where we replaced ng-bootstrap and needed to style needs to be checked in other browsers

**Comment by developpeurweb** [comment]
@tobi-or-not-tobi @Xymmer 
This seems like a webkit browser bug caused by gradients, it doesn't work for Safari or Mobile Browsers, so i've tried setting up a `-webkit-linear-gradient` alternative but still doesn't fix it.
This bug comes as a result of the `ng-bootstrap` removal which works for all browsers and also approaches the setup differently by using "half" divs that stretch its width to a certain percentage (instead of a gradient), is it possible to implement something like that with TS?
https://ng-bootstrap.github.io/#/components/rating/examples#decimal

![Screen Shot 2019-06-17 at 5 30 58 PM](https://user-images.githubusercontent.com/15113219/59638221-d0897e80-9125-11e9-8429-03a3ae99facc.png)

**Comment by tobi-or-not-tobi** [comment]
@developpeurweb I was able to fix this for safari, hoping this also fixes #3048.

**Comment by KateChuen** [comment]
Tested on dev17 on iphone 8+.
![IMG_8477](https://user-images.githubusercontent.com/45409515/59772966-c5943280-927a-11e9-9b19-66eb1da2a1ec.PNG)
![IMG_8478](https://user-images.githubusercontent.com/45409515/59772995-d6dd3f00-927a-11e9-88e7-6db6a23090d3.PNG)
