### ISSUE TITLE
improve customizing component service logic

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#2906]
Currently when customizing component service as provided Doku https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Customizing-CMS-Components is a bit difficult to override methods from the default service.

Eg. doing the following will hook new custom service but it will throw errors as methods from SearchBoxComponentService should be implemented also in CustomService. But there is no abstract logic or any way to find out which methods must be implemented in new custom service

```
SearchBoxComponent:{
          providers : [
            {
              provide: SearchBoxComponentService,
              useClass: CustomService,
              deps: [CmsComponentData, ProductSearchService, RoutingService]
            }
          ]
        }
```
## Environment Details

- Spartacus:  ~0.1.0-alpha.1
- Browser: chrome
- OS: Linux (centos7)

## error in the console (the error is obvious but the user had no clue that this method exists)

> ERROR TypeError: this.searchBoxComponentService.getResults is not a function
>     at new SearchBoxComponent (spartacus-storefront.js:14342)
>     at createClass (core.js:22152)
>     at createDirectiveInstance (core.js:22029)
>     at createViewNodes (core.js:23255)
>     at createRootView (core.js:23169)
>     at callWithDebugContext (core.js:24177)
>     at Object.debugCreateRootView [as createRootView] (core.js:23687)
>     at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (core.js:21508)
>     at ViewContainerRef_.push../node_modules/@angular/core/fesm5/core.js.ViewContainerRef_.createComponent (core.js:21619)
>     at ComponentWrapperDirective.push../node_modules/@spartacus/storefront/fesm5/spartacus-storefront.js.ComponentWrapperDirective.launchComponent (spartacus-storefront.js:4075)
>

**Comment by tobi-or-not-tobi** [comment]
Hi @mrSingh007, just FYI, we refactored the search box component and no longer provide a component specific service. Instead we implemented the logic in an application wide singleton service, and with that can use standard angular DI to provide a customer service. 

That being said, the question is still valid. In general when you like to provide a custom service, if we haven't used an interface for the service, you can extend the existing service, which should help. Otherwise, you're right, there's no easy way. We'll discuss if we want to introduce interfaces to have a clear contract in place.

**Comment by mrSingh007** [comment]
@tobi-or-not-tobi thanks. Then you may close this ticket if in the new release it will be improved

**Comment by Xymmer** [comment]
thanks for the feedback! closing
