### ISSUE TITLE
Product Image is missing on product detail page

### ISSUE THREAD

**Issue by valentinvieriu** [SAP/cloud-commerce-spartacus-storefront#3104]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

```
    "@spartacus/assets": "0.1.0-beta.3",
    "@spartacus/core": "0.1.0-beta.0",
    "@spartacus/storefront": "^0.1.0-beta.0",
    "@spartacus/styles": "0.1.0-beta.0",
```

## Steps to Reproduce

Visit https://stackblitz.com/edit/angular-pn7bpm and try a product detail page.
## Observed Results

The product image is missing.

## Expected Results
The product image should be there. See same code using an apha version https://stackblitz.com/edit/angular-ychytz

**Comment by Xymmer** [comment]
since it's thru stackblitz and we're not seeing it in our builds, likely some kind of stackblitz config issue, or media cors config.

**Comment by valentinvieriu** [comment]
Hi @Xymmer I doubt that might be. Here is another link: [sample](https://spartacus.cxlabs.dev/product/553637/NV10)
This is a little modified version of the app using 
```
    "@spartacus/assets": "0.1.0-beta.3",
    "@spartacus/core": "0.1.0-beta.1",
    "@spartacus/storefront": "^0.1.0-beta.1",
    "@spartacus/styles": "0.1.0-beta.1",
```

As you can see in the Network tab, a call fails to `https://api.czfr-cxlabs1-d25-public.model-t.cc.commerce.ondemand.com/rest/v2/electronics-spa/products/553637/references?fields=DEFAULT,references(target(images(FULL)))&referenceType=SIMILAR&lang=en&curr=USD`.
We are using SAP Commerce Cloud instance (Release 1811)

**Comment by tobi-or-not-tobi** [comment]
Hi @valentinvieriu the product data you'v normalised from the graphQl service is not returning the expected format. i understand this is hard to catch from your side, as you've delivered a valid object. We might be able to improve our type. 

The commerce backend has different media attributes, and the are exposed as:
- `product.images.PRIMARY.thumbnail`
- `product.images.GALLERY[0].thumbnail` 
- `product.images.GALLERY[0].product`

The uppercase property represents the type of media, some of them are an array. 

OCC actually returns a flat list of everything, which is why we converted this to a more semantic model. 

We'll create a ticket to improve the type safety here.
