### ISSUE TITLE
Drop refresh token from local storage

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3187]
We store the refresh token in the local storage which is a security issue.

**Comment by dunqan** [comment]
Also we need to make sure, that we won't break refresh logic in user token interceptor

**Comment by LTiger14** [comment]
Indeed the refresh mechanism will have to be altered. After discussion with @hackergil it's ok that the session will not refresh because of the absence of the refresh token.

**Comment by giancorderoortiz** [comment]
Please add QA steps

**Comment by giancorderoortiz** [comment]
Will need to test on mobile devices as well. Please update public server with this fix so that it's easier to test.

**Comment by LTiger14** [comment]
QA Steps:
- Login
- Open dev tools; go to > Application > open local storage > in the auth object you should not see `refresh_token`

Testing the refresh still works:
- In HAC change the config with these values
```
oauth2.accessTokenValiditySeconds=60
oauth2.idTokenValiditySeconds=60
``` 
- (1) Create a new user, check in local storage to see if token validity is 59 seconds (if it isn't add those config to local.properties and restart backend)
- Redo step (1)
- Refresh page & wait 60 seconds
- Do an action, you should be redirected to login
- Login, wait 60 seconds
- Do an action, you should see an error (401) but the refresh_token should refresh the access token and the action should work

**Comment by giancorderoortiz** [comment]
The refresh token itself is removed per implementation in this ticket. 🆗 
Further comprehensive testing is required to see what side-effects are now present because of this. ℹ️ 
Separate tickets will be created for issues found.

**Comment by chernatkin** [comment]
hi! sorry for commenting already closed ticket, but i have question regarding refresh token in local storage
Could you please explain more detailed what is the security issue with saving refresh token in local storage?

I figured out, that if i close  browser (firefox or chrome) then refresh token is lost and user logged out when access token expired
But in typical config for hybris access token is valid 12 hours, refresh token - 30 days,
but it makes no sense then to have refresh token then, because i think almost no one will have browser opened during more than 12 hours
