### ISSUE TITLE
StorefrontModule is missing dependencies

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3271]
If you want to create a custom storefront, you could avoid the `B2cStorefrontModule` and import the `StorefrontModule` to avoid default configurations. The `StorefrontModule` is lacking some fundamental imports, which must be fixed.

**Comment by hackergil** [comment]
I was testing this today. Here's what I found:

- In dev/prod mode, using our shell app from projects/storefrontapp there are no compilation errors but pages won't render since component definitions are not being imported (which is expected)

- Using a custom shell app and built libraries, it fails with the following error (in both dev and prod mode):
> ERROR in : 'cx-storefront' is not a known element:
1. If 'cx-storefront' is an Angular component, then verify that it is part of this module.
2. If 'cx-storefront' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<cx-storefront>Loading...</cx-storefront>
")

**Comment by tobi-or-not-tobi** [comment]
Most likely the cx-storefront component is not exported from the StorefrontModule. Can you double check?
