### ISSUE TITLE
Revisit lint rules

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#332]
Recently the HTML files are being formatted in a different way due to changes in prettier plugin for vs code.

Revisit the prettier rules in both the vs plugin and prettier config file to confirm current rules or redefine them. Also, reformat all html in one go, so that we don't have complicated file comparison

**Comment by tobi-or-not-tobi** [comment]
@hackergil @LTiger14 can we put this on hold until we've finished some work on the configurable and nested routes. @Platonn need a few more days, but since he touched a lot of files, it will not be possible to review otherwise. We'll keep you posted. 
@Platonn will create a small PR to make sure the team will ignore html for prettier for the time being.

**Comment by LTiger14** [comment]
This got bumped up in priority so I will start working on it.

**Comment by LTiger14** [comment]
Based on research and trial and error I noticed a few things that happen related to our prettier "status".

1. The ticket mentions that the rules are different for the extension and the cli. This is not the case. Based on the Prettier documentation, I was able to see that the extension will apply the settings as follow: 

> Settings will be read from (listed by priority): 1. Prettier configuration file 2. .editorconfig

Also, "the vs-code prettier settings will only be read if no config file is present". This means that the cli and extension do use the same configs.

2. There is a discrepancy in the Prettier version the extension and the cli are using. For example on vs-code I'm using the extension version 1.7.2 which is using Prettier version 1.15.2. On the other hand, the cli is using 1.14.3. This is a problem because the "opinionated" formatting is slightly different in these two versions. This is cause by bugs being fixed and new file type support.

What I can conclude is that based on point 2, there will alway be a risk of formatting discrepancy between vs-code and the pipeline even if they have the same configs as there is no way to ensure the pipeline and extension are using the same version. Another concern I have is that there a very few rules that concern html and there is no way to provide different configurations by file type. This could be a concern if we want for example html files with longer lines (html files tend to have longer lines because of the nesting of selectors).

This topic should be further discussed as a team.

**PS:** there is also this issue but I have not been able to reproduce.
