### ISSUE TITLE
Create new tests for payment (shipping and billing addresses)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3402]
following #3323

**Comment by kacperknapik** [comment]
we have to create 3 tests for payment details checkout step:
- [ ] both shipping and billing addresses are the same (checkbox checked)
- [ ] shipping address has the same country as billing address (checkbox not checked)
- [ ] shipping address has different country than billing address (checkbox not checked)

note: ideally, check Poland and Canada - because we are sure one of them doesn't have regions and the other does

**Comment by kacperknapik** [comment]
@Pucek9 	will help with this one

**Comment by giancorderoortiz** [comment]
A few cases I tested manually before:
1. Shipping address Canada. Billing address US. 
2. Viceversa. 
3. Same country for billing and shipping address. (Different states/provinces)
4. Usage of different dummy credit cards (See here: https://www.paypalobjects.com/en_AU/vhelp/paypalmanager_help/credit_card_numbers.htm)
5. Changing my mind and adding a different billing address or payment method before checkout.

**Comment by KateChuen** [comment]
The test "shipping address has different country than billing address"  - more specifically this step: should fill in payment form with different billing address (country with states)
needs a config in the backend for it to pass. 

Also make the steps decoupled. because if this step fails, it doesn't clear the payment form. It just keeps typing the card number on top of the previous one, so then the next steps will fail because of invalid card number. 

And if we do add the config, it looks like the test "should fill in payment form with different billing address (country without states)" will fail. 

So maybe it's not ideal to have it as E2E? Or we should add a script for changing the config in the backend? 

I'm currently running it against dev17. - It has been failing in the nightly builds. Can you take a look please?

**Comment by giancorderoortiz** [comment]
not a lot of success yet. 4 tests fail. 
![Screen Shot 2019-07-12 at 3 59 12 PM](https://user-images.githubusercontent.com/46171897/61155130-1edc3400-a4be-11e9-8a62-64dc4ffcc409.png)

**Comment by plabadie** [comment]
> The test "shipping address has different country than billing address" - more specifically this step: should fill in payment form with different billing address (country with states)
needs a config in the backend for it to pass.

This was since then fixed by GH-3715.  The required mapping labels are present in our environments

> Also make the steps decoupled. because if this step fails, it doesn't clear the payment form. It just keeps typing the card number on top of the previous one, so then the next steps will fail because of invalid card number.

tbd

> And if we do add the config, it looks like the test "should fill in payment form with different billing address (country without states)" will fail.
> So maybe it's not ideal to have it as E2E? Or we should add a script for changing the config in the backend?

This was a bug that was fixed since then. See GH-3687

I'm currently running it against dev17. - It has been failing in the nightly builds. Can you take a look please?

As of now, I can't repro failures on this test using dev17.  I do see it fails occasionally on the nightly run.  Perhaps the refactoring requested above would improve things?

**Comment by plabadie** [comment]
PR #3749
