### ISSUE TITLE
I can't navigate by letters in selects

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3469]
Navigation works correct but I'm not scrolled to focused option

**Comment by Xymmer** [comment]
@Pucek9 can you give more detail? i didn't understand

**Comment by Pucek9** [comment]
@Xymmer 
E.g. in country select after press key 'c' Canada will be focused, but we can't see that. 
![image](https://user-images.githubusercontent.com/8040837/60448187-698bbf80-9c25-11e9-83a8-f1737d6f1b37.png)
There should be added scrollIntoView on active option.

**Comment by Pucek9** [comment]
Additionaly press again probably should navigate to next country started with this letter. That is working only in Personal Details page (title select)

**Comment by Pucek9** [comment]
ng-select doesn't support key-down events, which can be used for scrollIntoView for marked option - additionally, that solution would be needing a wrapper for ng-select.

My proposal is using searchable select for large lists (e.g. country/region)
![image](https://user-images.githubusercontent.com/8040837/60581483-33fee780-9d87-11e9-9aa3-6497c82de4ab.png)

**Comment by RadhepS** [comment]
Dropdowns are now inconsistent. 
We have this implementation for the country dropdown but not for title or payment card selections.
Dropdowns should ideally be consistent throughout the application.

Perhaps this can be something we can discuss in a stand-up with the team.

**Comment by Pucek9** [comment]
> Dropdowns are now inconsistent.
> We have this implementation for the country dropdown but not for title or payment card selections.
> Dropdowns should ideally be consistent throughout the application.
> 
> Perhaps this can be something we can discuss in a stand-up with the team.

Yep, this is a proposal for large lists. IMO it's unnecessary to use it in title and payments. Let's discuss and decide.

**Comment by Matejk00** [comment]
Let's discuss this topic in seperated ticket #3652, probably we need @Xymmer to decide. 

For now we can merge this ticket and keep this solution only for long list selects like countries and states.

**Comment by KateChuen** [comment]
Tested on dev2. 
- On Countries & States/Region Lists, I'm able to search by typing in the dropdown menu. 
- On Title (on both address book page and personal details), I am only able to get the first result by typing a letter. Typing the same letter again doesn't focus on the next option. For eg, if I type M, it will go to Mr, typing M again doesn't go to Mrs, Miss etc. 
- Same thing with Payment cards list. It would be an improvement and perhaps these will be fixed in ticket #3652 when they'll make all the dropdown menus consistent. Added a comment there.
