### ISSUE TITLE
[Xiaomi/Firefox] - Buttons Cancel and Save are tightly pressed together

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3521]
Cancel and save buttons should have some space between them.

![image](https://user-images.githubusercontent.com/11735817/60511195-aad9a900-9cd1-11e9-8a2e-dbe2b808839d.png)

**Comment by developpeurweb** [comment]
This is getting fixed in GH-3598 as a test case

**Comment by developpeurweb** [comment]
Please re-test with theme `calydon` enabled

**Comment by KateChuen** [comment]
This is fixed for update password page indeed. 
<img width="463" alt="Screen Shot 2019-09-18 at 2 11 37 PM" src="https://user-images.githubusercontent.com/45409515/65174392-d17cc580-da1e-11e9-9998-a370553ca49c.png">

And I see that only the update password page has been implemented with the calydon theme so far. 
![Screen Shot 2019-09-18 at 2 16 04 PM](https://user-images.githubusercontent.com/45409515/65174429-e35e6880-da1e-11e9-91a0-f7bf6181b8b6.png)

Which is why other myaccount pages still have this issue.
<img width="432" alt="Screen Shot 2019-09-18 at 2 12 35 PM" src="https://user-images.githubusercontent.com/45409515/65174452-eeb19400-da1e-11e9-9c54-605df0d40886.png">

So I will leave this ticket open, until all the pages have been fixed.
