### ISSUE TITLE
Check if failing E2E tests are false positive, if so tell Gil we can release

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3525]

**Comment by bgambocjaviniar** [comment]
tested on dev-17 

- mobile - checkout-flow is just inconsistent, therefore false-positive
- mobile - order-history-no-orders is worrisome, I think it is just an error related to the test, because it says bad credentials when trying to login after registering, will test manually.
- payment-method is inconsistent, therefore false-positive (too slow / too fast)
- sitecontext - language-myaccount is checking for the wrong month (new month is july, and its checking for june), therefore false-positive
