### ISSUE TITLE
Update forgot password cms descriptions

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3532]
"updatePassword" page has "Update Forgotten Password Page" but that's actually for when you are changing your password. 

In spartacus sample data:
- Change that to "My Account Update Password page".
- Change name of resetPassword page to "Reset Forgotten Password" page.

![image](https://user-images.githubusercontent.com/4998145/60531727-985b7180-9cc9-11e9-9610-931ae9acd25d.png)

**Comment by LTiger14** [comment]
PR: https://github.tools.sap/cx-commerce/c3po-legacy-spartacussampledataaddon/pull/6

**Comment by giancorderoortiz** [comment]
Will this fix the wrong links seen in reset password received email?

**Comment by LTiger14** [comment]
No this will not fix wrong links in reset password received email

**Comment by LTiger14** [comment]
QA Steps:

**Comment by KateChuen** [comment]
Tested on dev17. 
- Update password OK. 
- Able to reset password. Even the link in the email is ok (had to configure it in the backend to get the right baseUrl which is normal). Otherwise, it's using the https one instead (so if we start our app with ssl, should be transparent). Perhaps the issue with the wrong link you're referring to is fixed in #3526
- Accessing the same link again after successfully resetting the password redirects the user to the homepage.
