### ISSUE TITLE
TM - XSRF

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3616]
**Spartacus Threat Modelling Workshop.**
Date: June 14, 2019.
Participants: Bill, Gil, Tobias, Stan, Hernando, Felix, GC

_SAP Product Standard Required Compliance:_
https://wiki.wdf.sap.corp/wiki/display/PSSEC/SEC-223

_Threat Pattern:_
Threat: Attackers could exploit CSRF/XSRF vulnerabilities to submit requests (retrieve confidential data, modify confidential data) on behalf of the legitimate user and remain unnoticeable by any log mechanism.

(As informed/discussed/reported by security team during workshop)
**TM Comments:**

1. THREAT: no XSRF in place by default.

**TM Required Actions:**

1. Evaluate XSRF support from APIs / request functionality perhaps.

**Comment by giancorderoortiz** [comment]
Sounds critical to me.

**Comment by tobi-or-not-tobi** [comment]
See https://angular.io/guide/security#xsrf

**Comment by giancorderoortiz** [comment]
Will be addressed in the refactoring work described here: GH-1018

**Comment by meeque** [comment]
IMHO the issue of XSRF is rather distinct from the session management improvements discussed in GH-1018, and should be treated here separately.

Luckily, Spartacus seems to be operating in an environment where additional security controls (like anti-XSRF-tokens) may not be required. The [OWASP XSRF Prevention Cheat-Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html) says:

> A CSRF attack works because browser requests automatically include any credentials associated with the site, such as the user's session cookie, IP address, etc.

Some literature speaks of "ambient credentials", when the browser includes them automatically. Other examples of ambient credentials are HTTP Basic Auth and TLS Client Certificates.

Afaik, the server-side APIs that Spartacus relies on (OCC2) do not accept ambient credentials when authorizing requests, most notably they do not accept Cookies. Instead the APIs rely on oAuth2 Access Tokens. Those are not ambient credentials, because the browser does not automatically include them into requests the APIs. 

Instead, the client-side application (Spartacus) is responsible for adding Access Tokens programmatically, where needed. Thus, a valid Access Token will never be present on any request that is truly cross-origin. In a way, the Access Tokens that Spartacus uses already serve both as session ids and as anti-CSRF-tokens.

If the above assumptions can be confirmed for all APIs that Spartacus consumes, there should be no need for the server-side APIs to enforce additional anti-CSRF-tokens. In fact, the whole OCC2 API was designed under that assumption.

**Comment by meeque** [comment]
Regardless whether additional anti-XSRF-tokens may be necessary or not, a typical single-page-application (Spartacus) needs to take additional precautions to prevent XSRF. In particular, Spartacus needs to ensure that it does not trigger any state-changing Ajax requests (aka transactions) without appropriate user interaction.

There are certain conditions where Spartacus triggers Ajax request without explicit user interaction. For instance, when a user merely navigates to a Spartacus page this is not an explicit interaction. (The user could have been coerced into navigating to Spartacus by a sneaky link from a malicious website.)

Most (all?) URL-based navigation in Spartacus is handled by Angular routing. Thus it is essential that Angular routing by itself does not trigger state-changing Ajax requests. In other words, mere navigation to and display of a view must not trigger a state-changing Ajax request. 

For example, Spartacus must not provide any deep-links that would put a product into a cart, check out, or modify account data without additional user interaction. This guarantee must be enforced programmatically! Ideally, a respective rule should be added to the coding-standards or definition-of-done of Spartacus.

When using standard-compliant server-side APIs (like OCC?) all Ajax GET requests can be considered non-state-changing. Thus Angular routing and view rendering must restrict itself to GET requests!

**Comment by dunqan** [comment]
1) Agreed, we don't need XSRF token when using access token as a programatically added bearer token. We were considering alternative solutions, including storing token or session id in a cookie, but the final conclusion (and most up to date solution) I believe is using Authorization Code Grant Flow with PKCE + Silent authentication (to not have to store token in an insecure browser storage) -> but it has to be supported by oauth server (which remains unknown atm)
2) Regarding XSRF precautions, afaik the only "state changing" route we have in spartacus is the logout route (which doesn't call a backend atm) - but a very good point, it would be good to verify it and make sure, we won't introduce it in the future.

**Comment by giancorderoortiz** [comment]
Closed for now given above discussion.
