### ISSUE TITLE
CheckoutConfigService not exported

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3619]
CheckoutConfigService isn't available in public API. It should be exported.

**Comment by psmul** [comment]
Steps for QA:
1. Run clean angular app
2. Import Spartacus core libraries
3. Import CheckoutConfigService
4. Run & build application

**Comment by KateChuen** [comment]
@psmul Can I have a bit more info please?
I've imported Spartacus core libs in package.json
I've imported CheckoutConfigService in app.module.ts
But.. using a clean angular app, it should be out of the box, and available in spartacus core? At least that's what I understood... 

So, I have this: 
> import { ConfigModule, CheckoutConfigService } from '@spartacus/core';

But looks like it's not there. Because I'm getting this: 
> error TS2305: Module '"../../node_modules/@spartacus/core/spartacus-core"' has no exported member 'CheckoutConfigService'.

but looking for the file, it looks like it would be more in the storefront lib. So I also tried this:
> import { B2cStorefrontModule, defaultCmsContentConfig, CheckoutConfigService } from '@spartacus/storefront';

And it still does not work for the same reason. 

So my question is, where should I be importing it? And how? 
And if I import it, I should be using it somewhere?

**Comment by psmul** [comment]
@KateChuen Okay, after consultation with a team, testing this one will be more tricky that I assumed. We will take care of testing this one, as it's impossible to test it now via simple import.

**Comment by Zeyber** [comment]
Checked and works. We can now use paths like the following with CheckoutConfigService included:
`import { CheckoutConfig, CheckoutStep, CheckoutConfigService } from '../'`
