### ISSUE TITLE
Checkmarx - Storefinder - Client DOM XSS

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3630]
**Scan Date:**
June 18, 2019.

**Report**
https://cx.wdf.sap.corp/CxWebClient/ViewerMain.aspx?scanId=4547096&ProjectID=63198

**File:**
\cloud-commerce-spartacus-storefront-develop\projects\storefrontlib\src\cms-components\storefinder\components\store-finder-list-item\store-finder-list-item.component.html

**Line:**
14,16,19,4

**Violations:**
4

**Checkmarx Severity**
High

**Issue:**
Missing input sanitation of "location". Vulnerable to DOM XSS attack.

**Comment:**

Method at line 1 of cloud-commerce-spartacus-storefront-develop\projects\storefrontlib\src\cms-components\storefinder\components\store-finder-list-item\store-finder-list-item.component.html gets user input for the location element. This element’s value then flows through client-side code without being properly sanitized or validated and is eventually displayed to the user in at line 1 of cloud-commerce-spartacus-storefront-develop\projects\storefrontlib\src\cms-components\storefinder\components\store-finder-list-item\store-finder-list-item.component.html.This may enable a DOM XSS attack.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-07-10 at 5 27 43 PM](https://user-images.githubusercontent.com/46171897/61006324-0c37f280-a338-11e9-948b-2096555555fe.png)

**Comment by gladius-mtl** [comment]
Need to double-check the input to see if it's sanitized.

**Comment by Platonn** [comment]
False positive. `location` (aka. point of service) is a local field of the StoreFinderListItemComponent (inherited from AbstractStoreItemComponent) and is an ordinary data model. NOT the `window.location`. So no sanitization is needed.

Won't fix

**Comment by giancorderoortiz** [comment]
Waiting for security confirmation.

**Comment by meeque** [comment]
I'd agree that this is a false positive but my rationale is different. While the `location` object is certainly distinct from `window.location`, it still contains dynamic data (aka user-inputs, aka tainted data). 

However, there is no risk of XSS here, due to the standard XSS protection mechanisms of Angular. In particular, the curly braces syntax of Angular templates performs HTML output encoding on all data that it emits to the DOM.

Is there any reason to believe that this built-in Angular mechanism is by-passed in this particular situation?

**Comment by giancorderoortiz** [comment]
Confirmed with Michael. A false positive.
