### ISSUE TITLE
Checkmarx - HSTS Header not Defined 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3632]
**Scan Date:**
June 30, 2019.

**Report**
https://cx.wdf.sap.corp/CxWebClient/ViewerMain.aspx?scanId=4547096&ProjectID=63198

**File:**
\cloud-commerce-spartacus-storefront-develop\projects\backend\mockgenerator\middlewares\singular.js

**Line:**
19

**Checkmarx Severity**
Medium

**Violations:**
1

**Issue:**
The web-application does not define an HSTS header, leaving it vulnerable to attack.

**Comment:**
The web-application does not define an HSTS header, leaving it vulnerable to attack.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-07-10 at 5 31 11 PM](https://user-images.githubusercontent.com/46171897/61006718-f971ed80-a338-11e9-9b90-0a1c8471d197.png)

**Comment by tobi-or-not-tobi** [comment]
Can we leave this code out of the scan? The mock generator hasn't been touched since a year, but more importantly we do not use this module in our production builds and library distribution. I believe we should com up with a list of exclusions of the scan to ensure we're not wasting time on non-issues.

**Comment by giancorderoortiz** [comment]
I agree.
