### ISSUE TITLE
Homepage components broken after logging out

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3761]
## Environment Details

Tested on Mac/Chrome

## Steps to Reproduce
1. Navigate to homepage
2. Log in
3. Log out
4. Change the viewport to mobile view
5. Click on hamburger menu on left side
Result: It is blank
![Screen Shot 2019-07-24 at 3 17 55 PM](https://user-images.githubusercontent.com/34665674/61821887-4ddf9780-ae26-11e9-85dd-c19843b198f1.png)
6. Change viewport back to desktop view
Result: Banner is broken, elements do not appear
![Screen Shot 2019-07-24 at 3 19 57 PM](https://user-images.githubusercontent.com/34665674/61821984-88493480-ae26-11e9-89ea-1ee767f43d40.png)

Steps can also be done in reverse. Logging out in mobile for example.

**Comment by psmul** [comment]
For signing out there is call for slots, however with wrong parameter. When we call /pages one of the parameters is *pageLabelOrId=/logout* which value is wrong. This causes server to respond with 404.
```
{
      "message" : "No content page found matching the provided label or id: /logout",
      "type" : "CMSItemNotFoundError"
   }
```

Additional info: Login flow differs from Logout flow. This is noticeable in PageEffects (line 39) where (for login flow) property nextState returns undefined and for logout, it's an object with logout route data. This is caused by the fact, that login is straight redirect to another view, where logout has guard redirecting to home ("/").
Also as Stan pointed out, there might be a mismatch in order in which navigation resolves slower than NGRX effect refreshPage$.

**Comment by Matejk00** [comment]
Cannot reporoduce on current develop, seems to be fixed.
