### ISSUE TITLE
Close Account: Confirmation dialog does not close upon an error

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3773]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: Mac
Happens on: https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/my-account/close-account

**Steps to Reproduce**
- Setup your env, so it will generate a 500 on Close Account. (In this file: `/ycommercewebservices/web/src/de/hybris/platform/ycommercewebservices/v2/controller/UsersController.java` -> For `removeUser()` -> change the `@ResponseStatus` to `HttpStatus.INTERNAL_SERVER_ERROR`). Rebuild and restart your server.
- In SPA, Go to MyAccount -> Close Account
- Click on "Close Account". 
- And on the confirmation popup, click on "Close Account" again

**Actual Result**
- The error is displayed in the background, but the popup doesn't disappear.
And the screen remains like this. So you don't get the feedback whether your account has been closed.

<img width="1437" alt="Screen Shot 2019-07-25 at 11 04 37 AM" src="https://user-images.githubusercontent.com/45409515/61886340-825a5e80-aecd-11e9-8158-8df1bf9c9963.png">

- Upon refreshing the page, you're redirected to the login page, and if you try to login, then you get the message that your user has been disabled. 

- Or you can keep on clicking on the "Close Account" in the popup, and you'll see that the user is redirected to the login page in the background. But the popup remains.
<img width="918" alt="Screen Shot 2019-07-25 at 11 14 19 AM" src="https://user-images.githubusercontent.com/45409515/61886320-79698d00-aecd-11e9-9ed4-d16df53f259b.png">

**Comment by Xymmer** [comment]
Make sure popup closes if there is an error.

**Comment by bgambocjaviniar** [comment]
PR GH-4015

NOTE: this fix fixes what Bill said above, BUT, looking at the code, and if we were to change HttpStatus.OK to HttpStatus.INTERNAL_SERVER_ERROR for other functions for other my-accounts, then it would be a problem. Because currently, the modal closes upon clicking close account when there's an error, but it won't redirect you to login as intended, because success = false.

This implementation is the same in other my-account implementations, therefore if we would change the status to a bad status for testing, it would not redirect you to the intended spot, and it will still successfully work under the hood. 
For example, this ticket closes the account, but when there's an error, the modal stays on. When you refresh, you got redirected to the login as intended. This case will be the same for other my account pages.

**Comment by bgambocjaviniar** [comment]
QA:

- Setup your env, so it will generate a 500 on Close Account. (In this file: /ycommercewebservices/web/src/de/hybris/platform/ycommercewebservices/v2/controller/UsersController.java -> For removeUser() -> change the @ResponseStatus to HttpStatus.INTERNAL_SERVER_ERROR). Rebuild and restart your server.
- In SPA, Go to MyAccount -> Close Account
- Click on "Close Account".
- And on the confirmation popup, click on "Close Account" again
- Make sure Modal Closes

- Don't worry about clicking close account again and when it redirects you back to login and signed out. It is like this due to setting the response status to an internal server error.

**Comment by KateChuen** [comment]
Tested on dev10. 
Now the close account modal closes. 
And like Brian said, we have to click on "Close Account" again for it to redirect to the login page. 

![Screen Shot 2019-08-30 at 2 53 17 PM](https://user-images.githubusercontent.com/45409515/64045765-20c68900-cb38-11e9-866e-fa74e01e7f4e.png)
