### ISSUE TITLE
Hook schematics into the main package.json

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#3825]
The goal of this issue is to investigate how to add schematics to the main `package.json`'s `build:core:lib` and `test:core:lib` scripts. By doing this, the CI can notify us about any failing test or if schematics build fails.

**Comment by hackergil** [comment]
The intention of the schematics is to install spartacus from published libraries. This will be redundant for every build since it won't validate your current codebase.

**Comment by dunqan** [comment]
My PoV:
1. Agreed, schematics should not be included in `build:core:lib`, because are not relevant to it
2. We probably also don't need them in `test:core:lib` (from the same reason above)

But 
1. It would be recommended to include their its tests in the pipeline (by modyfying 'ci-scripts/unit-test-sonar.sh')
2. Trying to satisfy it's dependecies from main `package.json` if possible (so no additional `yarn install` ahs to be performed in schematics directory)
