### ISSUE TITLE
Infinite scroll [master]

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3882]
see project: https://github.com/SAP/cloud-commerce-spartacus-storefront/projects/54

**Comment by tobi-or-not-tobi** [comment]
A few remarks on infinite scrolling:
- Infinite scroll on PLP has the disadvantage that uses who want to scroll to the footer of the page are never able to, since there's a continuous stream of products coming. A few years back the ecosystem seem to be avoiding infinite scrolling on commerce pages for this reasons. Nowadays i've seen examples where the UI allows for both reaching the end of the page as well as filling in products into the list. 
- An alternative to automatically loading products, is to explicitly ask for "more". With this effect, the user is more in control
- An infinite scroll makes navigation more complex; if the user navigates from a product of the 2nd list of products (after infinite scroll event), reaches the PDP, and navigates back, what happens? Do we reproduce the long list (besides the general concern of the scroll position? 
- Whenever infinite scrolling is triggered, a visual indicator should appear. Ideally with a skeleton of the UI.

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4041

Master PR.
