### ISSUE TITLE
Action Links do not display as intended unless they contain a URL

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#4064]
I am implementing an infinite scroll feature and it will contain two buttons.

These are "Back to top" and "Show More".

![Screen Shot 2019-08-14 at 3 40 20 PM](https://user-images.githubusercontent.com/34665674/63050781-dc858880-bea9-11e9-9c43-1cfcc27a1655.png)

Below is how regular links work (basically action links that use lowercase letters)
![2019-08-14 15 44 59](https://user-images.githubusercontent.com/34665674/63051090-7fd69d80-beaa-11e9-8512-f85c0fdc4942.gif)

The code for this is below:
```
<p>
    <a
      [routerLink]="{ cxRoute: 'forgotPassword' } | cxUrl"
      aria-controls="reset-password"
      class="btn-link"
      >{{ 'loginForm.forgotPassword' | cxTranslate }}</a
    >
  </p>
```

Now if we remove the URL from the code snippet, we get:
```
<p>
    <a
      aria-controls="reset-password"
      class="btn-link"
      >{{ 'loginForm.forgotPassword' | cxTranslate }}</a
    >
  </p>
```
![2019-08-14 15 50 05](https://user-images.githubusercontent.com/34665674/63051433-39357300-beab-11e9-902a-2ea47026741f.gif)

Neither my "Back to Top" or "Show More" buttons contain any links and therefore they will appear as the example above. 

This can be resolved by applying CSS rules that will mimic what we are expecting. I'm unsure if this is what we want to do though.

![2019-08-14 15 53 23](https://user-images.githubusercontent.com/34665674/63051689-ac3ee980-beab-11e9-889f-e7b34a263e38.gif)

**Comment by developpeurweb** [comment]
@RadhepS since this is not really a link to be followed and the styling detects that, we can't use that style for this case

It seems we left out the _Action Link_ styling as it is only used in the PDP, and now it would be a breaking change, I've taken note of that for coming releases, but in the meantime you can try styling it as an **Action Button** which serves almost the same purpose and the style exists already.

Please try `<div class="btn btn-block btn-action">` you will find similar applications for this kind of button in the checkout process for adding addresses or payment methods or going back to the previous step. Code wise you can try to arrange it in the same way as it is in the bottom area of the checkout process.

**Comment by developpeurweb** [comment]
something like this:
![Screen Shot 2019-08-22 at 2 20 08 PM](https://user-images.githubusercontent.com/15113219/63539431-14af4b80-c4e8-11e9-85bd-f727afff4e23.png)
