### ISSUE TITLE
Node.js slowly displays SSR application

### ISSUE THREAD

**Issue by artem-zur** [SAP/cloud-commerce-spartacus-storefront#4073]
Following a discussion on the Spartacus Slack, it was noted that Node.js slowly displays SSR application which are using Spartacus packages.

## Environment Details

- Spartacus:  *-1.0.4
- Browser: Chrome
- Other environment details: Node.js 12.0.4

## Steps to Reproduce

1. Create custom application which are using Spartacus packages.
2. Configure SSR based on provided manual - https://sap.github.io/cloud-commerce-spartacus-storefront-docs/server-side-rendering-in-spartacus/.
3. Build application.
Start application with Node.js.
4. Open application's main page in browser.

## Observed Results

Doesn’t matter which environment is using - application rendering always takes 20 seconds.

## Expected Results

Application rendering takes optimal time for user and search crawlers (< 5 sec).

## Additional Information

https://spartacus-storefront.slack.com/archives/CD16V16FR/p1565861743157500

**Comment by dunqan** [comment]
@artem-zur Could you please provide more details about your setup?
Especially regarding node js server vs backend instance, how they were hosted, i.e. were they both local, in the same network or remote?

Also, very helpful for identifying the possible bottleneck, would be measurements of raw occ http respones times -> that IMO would be the first suspect. 
You can also add http interceptor to spartacus app, that could simply log all http requests (when they start and finishes) to get a general idea, how impactful they are.

**Comment by dunqan** [comment]
And in general, for SSR you should use some caching mechanism. You can safely cache ssr responses, because they do not contain any user specific or personalized data.

In case of spartacus, to render home page for example, your node.js app will have to ask backend for some basic data like languages, currencies, then page data, wait for the response, then load data related to component. i.e. if you have carousel on home page, your node js app will have to load products data for all the products you would like to see on in your render.

So the time of rendering depends on many factors, but the most prominent ones are:
- network bandwidth between node js instance and occ backend
- occ backend performance (how fast it can handle all needed requests)
- amount of data that needs to be loaded on specific page

Although we plan do to a lots of the optimizations for data loading in near future (https://github.com/SAP/cloud-commerce-spartacus-storefront/issues?q=is%3Aopen+is%3Aissue+label%3Aperformance) the fact is, that whatever we'll do, the TTFB (Time To First Byte) will always be slower when using SSR, unless you'll cache it. (edited).

In our internal testing we get something like 3 seconds for home page with raw SSR, which might not be 20 seconds you were observing, but it's also unnacceptable for production scenarios (it would both degrade user experience and SEO significantly). Just enabling nginx proxy cache in nginx server we put in front of our deployment, improved measured performance by sth like three hundred times.

**Comment by dunqan** [comment]
Closing for now, please re-open if needed.

**Comment by artem-zur** [comment]
@dunqan,

Thank you so much fo such detailed answer, all information provided by you is very useful. In our situation it was a bottleneck in custom application login, it was already fixed and we have 2.5 seconds for Home Page now.

We also already have Nginx Proxy Cache for static files in front of our application, but if you have some time, can you please provide more details about caching for SSR. Where we should place it ? Maybe you have some recommendations ?

Thanks in advance!
