### ISSUE TITLE
SimpleResponsiveBanner does not show image if media type 'tablet' is not present

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#4115]
SimpleResponsiveBanner does not shows image if media type tablet is not present in response? (even though 'desktop' and 'mobile' together or alone are present)
for example for this response, the banner will not be rendered:

```
"component" : [ {
               "typeCode" : "SimpleResponsiveBannerComponent",
               "name" : "test",
               "container" : "false",
               "media" : {
                  "mobile" : {    // not displayed as tablet is not present
                    --
                  },
                  "desktop" : {   // this image also not displayed
                    --
                  }
               }
```

## Environment Details

- Spartacus:   
      "@spartacus/assets": "~1.0.4",
      "@spartacus/core": "~1.0.4",
      "@spartacus/storefront": "~1.0.4",
      "@spartacus/styles": "~1.0.2",
- Browser: Chrome
- OS: Linux

## Offer to Fix
NO

**Comment by tobi-or-not-tobi** [comment]
Just to give bit of background here:

We like to render responsive images for banners. While we can do this in various ways, we prefer to use web standards, using the `image.srcset` (https://caniuse.com/#search=srcset). In order to ensure we support other engines (other browsers, crawlers) as well, we keep creating the `image.src`. The `image.src` could be driven by an explicit media format, but in case there's no explicit format given, we fallback to a default value... which is the tablet format. The problem (which is rightly reported with the issue), is that in case there's no format given for the tablet format, the full image isn't rendered. 

We will change the logic to fallback to any of the given formats, ideally we take a image with more resolution to ensure crawlers get a fairly large image as an input.
