### ISSUE TITLE
Implement a link in the footer for anonymous consent banner

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#4429]
# General

Implement a link in the footer that will open the anonymous consent details modal dialog.

See master ticket for more details: #3800

Create a PR against the master feature branch.

## Wire frames

https://98qkkl.axshare.com/#g=1&p=m_anonymous_consent_behavior_sticky_icon

## Behaviour

Clicking on the button should open the anonymous consent details modal dialog. 

## Component

The `AnonymousConsentStickyComponent` pulls anonymous consents from the store and it provides them as an `@Input()` to the `AnonymousConsentsDetailsDialogComponent`.

### Visible

This link in the footer should be visible only when an anonymous user is browsing Spartacus, and it should be present on every page they visit.

### Hidden

This link in the footer button should be hidden in cases when:

- the user is logged in
- the anonymous consent banner is displayed to the user

**Comment by Manurod2018** [comment]
I told Anthony we needed to look at another solution, mainly for 2 reasons: 
-	We already have a sticky icon for back to top.  
-	Having the sticking button always visible on the screen can very annoying, especially since it is just for the case where the user changes his mind. He might not want to do so and will most probably want to get rid of this button instead. 

Nik had actually a good idea: add a link to the footer, so the option is there but not as disruptive.

**Comment by znikola** [comment]
PR: #4754
