### ISSUE TITLE
Error when synchronizing  spa-electronics catalog

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#4500]
When synchronizing the spa-electronics content catalog it fails. This is just after setting it up. Seems to be an issue with the ProductReviewTabs component?

**Comment by mazamcodes** [comment]
Removing my name since work not yet started and re-assigned to other higher priority issues.

**Comment by Xymmer** [comment]
should i move this back to 'to do'?

**Comment by WeizhengSap** [comment]
Tested on my local. There is no failure. 
In log:
<img width="1095" alt="Screen Shot 2019-09-30 at 4 31 22 PM" src="https://user-images.githubusercontent.com/44440575/65915643-d425d600-e3a1-11e9-82cf-52f6b6a769c7.png">

In backoffice:
![Screen Shot 2019-09-30 at 4 45 50 PM](https://user-images.githubusercontent.com/44440575/65915657-da1bb700-e3a1-11e9-9793-ab704ccc648b.png)

**Comment by akumar-wtc** [comment]
we faced this issue while after setting up new base store and site .... while doing sync from normal content stage catalog to spa content stage catalog.  

INFO  [SyncWorker<000000RT 1 of 1>] [AbstractItemCopyContext] type class change class de.hybris.platform.cms2.jalo.contents.components.CMSFlexComponent -> class de.hybris.platform.acceleratorcms.jalo.components.JspIncludeComponent is not allowed since types are not compatible

it came for 33 items
