### ISSUE TITLE
User should not be able to add to cart if product does not have a price

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4877]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**

 I don't remember the exact steps, because I've been playing with the prices. I'll try again tomorrow and put the exact steps. But I think it's these:
**_Scenario 1_**
- remove the price rows from a product in the online catalog in backoffice. 
- Go to pdp page of the product
- Add to cart
- Go to cart page -> The product is $0.
![Screen Shot 2019-10-07 at 3 12 18 PM](https://user-images.githubusercontent.com/45409515/66347072-7c4b1a00-e921-11e9-94ce-4bfe61f51624.png)

**_Scenario 2_**
- Add a price row to that product in the online catalog in backoffice. 
- GO to pdp page of the product.
- Add to cart
- Remove the price rows from a product in the online catalog in backoffice. 
- Go to cart page
- Try to remove the product, update the qty or checkout -> cannot do any of these, so user is stuck with that cart and cannot do anything with it.
![Screen Shot 2019-10-07 at 3 19 58 PM](https://user-images.githubusercontent.com/45409515/66347080-810fce00-e921-11e9-817f-5fb917ffa323.png)

**Actual Result**
In Scenario 1, user should not be able to add to cart if the item does not have a price. So either, disable to button or give an error. 

In Scenario 2, maybe display a message to the user to remove the item from cart and allow him to remove it from cart, and not proceed with checkout. Or remove it from cart for the user.

**Comment by Xymmer** [comment]
There's a difference between no price and a price of 0 too i assume...
Proposing we:
- disable add to cart whenever price doesn't exist
- remove item from cart if price doesn't exist (for example, a product was added and then price was changed) - display a message in this case like "The product xyz was removed due to an error." This is a weird case but possible I guess. I'm wondering why the backend cart doesn't handle this and reject adding to cart.

**Comment by WeizhengSap** [comment]
I got an error message `Cart model 00000012 was not calculated due to: No price defined for product: ProductModel (8796193882113@27)` in Scenario 1. So, product is not added to cart.
In Scenario 2, there is also an error message. 
I don't think we should disable the "add to cart" button, because if there is no price (not 0.0) for a product, then it is the product setting error in backend. It should be fixed in backend. 
The only property that determine whether "add to cart" button disable or not is `purchasable`. If product is purchasable, then it should be able to be added to cart.

**Comment by KateChuen** [comment]
I've tried to reproduce it today but I see a different behavior today.
- If you were already on the pdp, and the price is removed, then you can add the item. But then after refreshing the page, the item is removed from the cart, which is ok. The error message could be nicer though. (at 1:45min)
- Then if you keep trying to add an item, it looks like it wasn't added. But then when you add the price row again, and add the item, it adds 2 items (at 4:05)

I can't attach the video here, will send it to Wei.

**Comment by KateChuen** [comment]
I managed to reproduce the $0.00 issue. but I still haven't pinned down the exact steps. 
I think the user needs to be logged in.

**Comment by KateChuen** [comment]
After talking to Wei, conclusion is: 
When the product does not have a price, the status will be "check". When that's the case, the product isn't visible to the user, so he cannot add it to cart. 

However, if the user already had the product in his cart, prior to removing the price and changing the status to 'check', this ends up in a non-functional cart. The user cannot remove the item, update the qty or proceed to checkout. So basically, the user can no longer shop at this point, which is not good for business :) Wei said it's a backend issue. So opened this ticket: https://jira.hybris.com/browse/C3PO-1917

**Comment by cgowez** [comment]
Hi @KateChuen we're having a similar issue with SAP Commerce 1905 and Spartacus, I do not have access to see ticket https://jira.hybris.com/browse/C3PO-1917, I would like to know what was the conclusion of this, if this is OOTB behavior and we should customize disabling add to bag button when the product does not have a price? 
I don't think it is a good idea changing the status of the product to "check" since some clients want to still display products for SEO purposes.
Let me know your thoughts, thanks.
