### ISSUE TITLE
SonarCloud, what's it all for? - missing configuration for PR

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#4916]
It wasn't informing us in pull requests, because we are missing some configuration: https://sonarcloud.io/documentation/analysis/pull-request/

Let's fix that and check then if that gives us enough value.

**Comment by hackergil** [comment]
I can see sonarcloud analysis by pull requests, and information on github is correct. Example:
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=new_duplicated_lines_density&pullRequest=5055&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fcore%2Fsrc%2Fauth%2Fstore%2Feffects

Also, based on the URL provided above, "Chances are that you don't need to read this page further since those integrations handle the configuration and analysis parameters for you."

So I am not following. What is the problem we are trying to solve with this?

**Comment by marlass** [comment]
Hmm, can we create some PR with bugs that would cause the sonar cloud to fail and block the PR?

**Comment by marlass** [comment]
This sonarcloud reporting is strange.

Example PR with errors: https://sonarcloud.io/dashboard?branch=feature%2Ffail-sonarcloud&id=sap_cloud-commerce-spartacus-storefront

If sonarcloud fails then it returns `exit code 1` in unit tests script which results in failed Travis jobs. Sonarcloud never finishes in that case. Also, you can't see issues in sonarcloud dashboard, when script fails.

Disabling mandatory checks for sonarcloud won't help in a case of external contributions. 

On the good side, sonarclouds checks some things in our code and finds new bugs/vulnerabilities :)

**Comment by hackergil** [comment]
So there is no missing configuration for PRs, reports are being generated as they should. Can we close this ticket since there is a follow-up ticket for the external PRs?

**Comment by marlass** [comment]
The only problem is that I can't find the report for this issue. I don't see it in dashboard and in travis job I see only exit code. No details about errors. So it isn't helpful for developers without this report. Do you know where can I find it for this PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5295 ?

**Comment by hackergil** [comment]
Sonar Report is not being generated because the unit tests are not passing. You need to add some sonar violations but unit tests, linting and prettier have to pass.

**Comment by marlass** [comment]
Yep. The report informs about vulnerabilities/bugs. Closing this ticket.
