### ISSUE TITLE
ASM search results: when too many matches (spike needed)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5016]
Accelerator ASM displays 12 results:
![image](https://user-images.githubusercontent.com/4998145/66866611-a0cd7480-ef67-11e9-8e01-7b720fb98809.png)

Spike:
- Are their paginated results returned from api call
- If so can we paginate the list, make it infinite, whatever, so you can see more results
- I assume we don't want to replicate the behavior where you hit Enter and see a whole page of paginated results.

**Comment by Xymmer** [comment]
Even displaying three dots or a message stating "too many results, narrow your search" is fine.
Patrick will take a look at the api and see what's available.
Also, the customer list feature might be the answer to searching through a lot of customers.

**Comment by plabadie** [comment]
The accelerator UI does not support paging or any mechanism that allows more than 20 results to be displayed.  There are no visual indication that the query may have yielded more results.  This is by design.

The customer search API behavior is consistent with the ASM accelerator UI: while it is possible to set the max result size via the `pageSize` parameter, no paging or total results indication is provided beyond the pageSize result limit.

We could at best display a visual indication that we are displaying the max results we can if we insist on adding feedback.

**Comment by plabadie** [comment]
We agreed we don't intend to add such feedback for now in GH-5013
