### ISSUE TITLE
[wait for backend fix]CartPage: Promotions disappear when we change currency

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#502]
## Environment Details

- Spartacus: develop branch
- Browser: chrome Version 70.0.3538.110 (
- OS: MacOS 10.14.1
- Device:
- Other environment details:

## Expected Results
Promotions should still be applied.

## Observed Results

When we first change from USD to JPY, the promotions message is still displayed (with unlocalized parameters), the the amount of promotion applied is 0.
When we change it back to USD, the promotions message is disappeared, and the discount is 0.

## Steps to Reproduce
- Go to Homepage
- Add a product with promotions to cart, for eg: http://localhost:4200/product/816780
- Go to Cart Page
![cartpagebeforecurrencychange](https://user-images.githubusercontent.com/45409515/49380394-93a4ef80-f6df-11e8-9305-90435a9b8759.png)
- Change the currency to JPY
-- The parameters in promotions message are not localised.
-- The promotion amount is 0.
![currencychangedtoy](https://user-images.githubusercontent.com/45409515/49380397-943d8600-f6df-11e8-9bcf-f9a51dd3d4a2.png)
- Change the currency back to USD
![currencychangedbacktousd](https://user-images.githubusercontent.com/45409515/49380396-93a4ef80-f6df-11e8-8842-1503f8f76e83.png)

**Comment by Xymmer** [comment]
this is one might be a bit complex, says Kacper

**Comment by KateChuen** [comment]
Still happening on dev17.

**Comment by WeizhengSap** [comment]
This issue is not in SPA side. It is an occ issue. The promotion is not applied to JYP. 
![Screen Shot 2019-05-31 at 4 47 43 PM](https://user-images.githubusercontent.com/44440575/58734001-322ab880-83c4-11e9-924b-c48f3130f5a6.png)

![Screen Shot 2019-05-31 at 4 53 25 PM](https://user-images.githubusercontent.com/44440575/58734169-a1a0a800-83c4-11e9-9c4e-26960a0a0896.png)

After changing from JYP back to USD, this promotion is not applied, and the "totalDiscount" value become 0. It also comes from occ.
![Screen Shot 2019-05-31 at 4 56 21 PM](https://user-images.githubusercontent.com/44440575/58734285-09ef8980-83c5-11e9-9cec-a3e9dc2beb86.png)
