### ISSUE TITLE
Revert to checkboxes + 'x all' fix links

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5104]
In both anonymous and logged-in-user consents, switches to the right were used. We should have stayed with standard checkboxes on left side. Sorry to ask but let's switch it back :)
The old code is still there because Nik added feature flags.

Example mockup:
![image](https://user-images.githubusercontent.com/4998145/67319240-a92f2d80-f4da-11e9-89e3-9c51ffae074e.png)

Notes about this:
- The description (the text underneath the 'name') should be a few points smaller
- I'd expect that I can click the checkbox or any part of the name, but not necessarily the description, to select the check box
- The Reject/Accept text is changed to Select all and Clear all and no need for a vertical | bar
- Careful of what happens in mobile
- If the anon consent modal has too many consents, will it scroll?

**Comment by developpeurweb** [comment]
@Xymmer "standard checkboxes on left side" implies removing the accordions, can you please confirm this is what you want.
**Manu**, can you please sync-up with Bill to retrofit these mockups so they become official guidelines and post them in this ticket for the record.

**Comment by developpeurweb** [comment]
@Xymmer I'm just realizing, if you choose to remove the accordions, you don't my intervention, maybe just for code reviewing, but most of the refactoring can be done by a developer directly in the html by removing the accordions code, simplifying the checkboxes and unplug the styles... since checkboxes are already pre-styled as global form elements.

**Comment by Xymmer** [comment]
sounds good! thanks

**Comment by LTiger14** [comment]
Points from above: 

-     The description (the text underneath the 'name') should be a few points smaller : **This is a breaking change**
-     I'd expect that I can click the checkbox or any part of the name, but not necessarily the description, to select the check box: _Done_
-     The Reject/Accept text is changed to Select all and Clear all and no need for a vertical | bar: _Done_
-     Careful of what happens in mobile: _It looks great_
-     If the anon consent modal has too many consents, will it scroll?: _Yes_

**Comment by KateChuen** [comment]
Tested on dev17. 

- [x] Now checkboxes are used. 

- [ ] The description (the text underneath the 'name') should be a few points smaller
I'd expect that I can click the checkbox or any part of the name, but not necessarily the description, to select the check box -> _I don't see the name being displayed anymore. I see the description only._ 

![Screen Shot 2019-10-29 at 9 13 45 AM](https://user-images.githubusercontent.com/45409515/67771150-23f1ce80-fa2e-11e9-81cb-0d7bcb8087c4.png)

- [x] The Reject/Accept text is changed to Select all and Clear all and no need for a vertical | bar

- [ ] Careful of what happens in mobile -> _I think it's missing some padding on both sides for the consents_
![Screen Shot 2019-10-29 at 9 24 40 AM](https://user-images.githubusercontent.com/45409515/67771234-50a5e600-fa2e-11e9-8010-86a301abc579.png)


- [x] If the anon consent modal has too many consents, will it scroll?

**Comment by KateChuen** [comment]
- [x]  The description (the text underneath the 'name') should be a few points smaller 

- [ ] I'd expect that I can click the checkbox or any part of the name, but not necessarily the description, to select the check box -> Clicking the description also selects and unselects the checkbox. This is because they are the same 'component' i think. Because if the description is short, you'll see that it's displayed on the same line as the title. @Xymmer Your call! 
![Screen Shot 2019-10-30 at 11 43 14 AM](https://user-images.githubusercontent.com/45409515/67874207-fdee2c00-fb0a-11e9-8d84-345237ec3819.png)

 

- [x] Careful of what happens in mobile
