### ISSUE TITLE
Inconsistent customer email validation in ASM

### ISSUE THREAD

**Issue by djumalin** [SAP/cloud-commerce-spartacus-storefront#5109]
## Environment Details

- Spartacus:  develop, last commit f1f3c1d0d48fb640374f8ad559287e5933a19c0a
- Browser: chrome 77 
- OS: ubuntu 18
- Other environment details: ec 19.5.5

## Steps to Reproduce

1. open storefront with ASM mode
2. login as asm agent
3. try to emulate "empty" and "invalid" customer email

## Observed Results
Error messages appears in differnet places

## Expected Results
Error messages appears in same place

![image (2)](https://user-images.githubusercontent.com/31624278/67280849-bb0ed180-f4d6-11e9-92e8-40dfda6927d3.png)
![image (1)](https://user-images.githubusercontent.com/31624278/67280850-bb0ed180-f4d6-11e9-9002-600d17d4d5b5.png)

**Comment by plabadie** [comment]
Won’t fix

This behaviour is intentional.  It is a convention across the storefront that basic field validation messages (like a required field) appear next to the invalid form field, and processing error messages appear in the global error message area.

Moreover, starting a session with a non-existing customer will not be possible anymore with the planned ASM for Spartacus roadmap. The customer emulation UI will likely evolve to behave like it did in the accelerator: the agent will chose from a list of existing customers before the start emulation button is enabled.
