### ISSUE TITLE
Load 'electronics-spa' consenttemplates even for apparel-uk site

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#5192]
1. add currency in context:
```
context: {
        urlParameters: ['baseSite', 'language', 'currency'],
        baseSite: [
          'electronics-spa',
          'electronics',
          'apparel-de',
          'apparel-uk',
        ],
        currency: ['GBP']
      },
```
2. go to `apparel-uk` site. If the `apparel-uk-spa` is ready, you can go to `apparel-uk-spa`site. Both should be fine.
3. You will see the error message:
![Screen Shot 2019-10-28 at 2 57 08 PM](https://user-images.githubusercontent.com/44440575/67709116-aed1bb00-f993-11e9-88a1-abf942795050.png)
4. You will find this one is tried to be loaded:
![Screen Shot 2019-10-28 at 3 01 23 PM](https://user-images.githubusercontent.com/44440575/67709186-d32d9780-f993-11e9-87f1-67a4cfb61af5.png)

**Comment by tobi-or-not-tobi** [comment]
I can confirm this bug. I have the following sites configured, and when I browse to `/electronics-spa/en/USD/`, there's a 404 on `https://storefront.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/rest/v2/tobi/users/anonymous/consenttemplates?lang=en&curr=USD `

```
baseSite: [
          'tobi',
          'electronics-spa',
          'electronics',
          'apparel-de',
          'apparel-uk',
        ],
```

**Comment by znikola** [comment]
The issue is caused by the `LanguageChangeAction` that's being fired once the application starts. Technically, this is not correct, because the language is set at the beginning and not changed. There's a PR that proposes a change for this: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5225, but at the same time this is considered as a breaking change.
This issue could be solved in another way, by removing the anonymous consents effect that loads templates on the `LanguageChangeAction` and implementing a workaround.

**Comment by znikola** [comment]
PR: 5270
