### ISSUE TITLE
Minor Alignment Bugs For Coupons

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5196]
Using Chrome v77. Dev tools for simulating different responsive breakpoints. 
See images below

**Comment by giancorderoortiz** [comment]
Ipad Pro:
![ipadProd](https://user-images.githubusercontent.com/46171897/67710941-5bfa0280-f997-11e9-8420-77f01d8d1ac8.png)

**Comment by giancorderoortiz** [comment]
Iphone X. Horizontal. 
![iphoneX-horizontal](https://user-images.githubusercontent.com/46171897/67711111-ab403300-f997-11e9-82ca-20d4dc1a4d4c.png)

**Comment by giancorderoortiz** [comment]
Galaxy S. 
No spacing between different promotions and/or coupons. 
![galaxy-s](https://user-images.githubusercontent.com/46171897/67711342-2c97c580-f998-11e9-8b9f-2a02440b3fd6.png)

**Comment by giancorderoortiz** [comment]
In the case of long coupon names, not sure if it's broken down correctly. There are characters above the 'X'. 

![Screen Shot 2019-10-29 at 8 10 11 AM](https://user-images.githubusercontent.com/46171897/67766034-eb4cf780-fa23-11e9-8f34-cb2063cfd519.png)
![Screen Shot 2019-10-29 at 8 10 37 AM](https://user-images.githubusercontent.com/46171897/67766035-eb4cf780-fa23-11e9-9479-69421ae5ab97.png)

**Comment by mazamcodes** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5259

**Comment by KateChuen** [comment]
Tested on dev10.

The only thing which still looks like what GC reported, is the spacing between the coupon's descriptions. But each coupon description is on a different line. It just looks compact on a small phone. I don't know what can be done to address this.
![Screen Shot 2019-11-07 at 10 39 19 AM](https://user-images.githubusercontent.com/45409515/68407674-f73a6700-0151-11ea-9c86-c187e2455290.png)


Otherwise, the other issues are fixed. The Apply button on ipad pro:
![Screen Shot 2019-11-07 at 10 36 29 AM](https://user-images.githubusercontent.com/45409515/68407250-3c11ce00-0151-11ea-9b0f-82c06d6da6fa.png)

The applied coupons on iphoneX horizontally:
![Screen Shot 2019-11-07 at 10 38 57 AM](https://user-images.githubusercontent.com/45409515/68407417-88f5a480-0151-11ea-86d6-7c1b83194b49.png)

The long coupon names on Galaxy S5:
![Screen Shot 2019-11-07 at 11 26 34 AM](https://user-images.githubusercontent.com/45409515/68407550-c2c6ab00-0151-11ea-9bfd-0d6443edb384.png)

And iphone 6/7:
![Screen Shot 2019-11-07 at 11 22 02 AM](https://user-images.githubusercontent.com/45409515/68407562-c65a3200-0151-11ea-8976-fbdd426af141.png)
