### ISSUE TITLE
Update webAppliationInjector.js with the fixed version

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#540]
The current version of the webApplicationInjector.js has an error. We created a smart edit ticket for it: https://jira.hybris.com/browse/CMSX-8096. When smart edit fix this issue, we need update the webApplicationInjector.js.

**Comment by Xymmer** [comment]
Brian writes: I guess there was a miscommunication on the location of the webApplicationInjector. It seems like our source file was taken instead of the "built" version. The correct location is documented in our smartedit storefront contract page: https://help.hybris.com/1808/hcd/622cebcb444b42e18de2147775430b9d.html#loioe9340d1d3d3249849ff154731277069a

Their ticket was closed.
