### ISSUE TITLE
custom prefix in occ config is not used when configuring core library

### ISSUE THREAD

**Issue by munro-art** [SAP/cloud-commerce-spartacus-storefront#5488]
When configuring the core library with occ configs {prefix: '/some/path/'} is not working.

[https://stackblitz.com/edit/spartacus-core-only](https://stackblitz.com/edit/spartacus-core-only)

## Environment Details

- Spartacus:  1.3
- Browser: chrome

- Other environment details:8.2.4

**Comment by KateChuen** [comment]
We changed it to v2, and we see a response. Could you please provide more details?

`prefix: '/rest/v1/',` changed to `prefix: '/rest/v2/',`

**Comment by tobi-or-not-tobi** [comment]
@KateChuen confirmed, it does work, however if the `ConfigModule` is used before importing other modules, the deep merge behaviour of the `ConfigModule` "hides" the prefix config. 

I'll make a new improvement ticket to come up with a better API for the `ConfigModule`, so that customers will not be confused by the deep merge behaviour.

**Comment by tobi-or-not-tobi** [comment]
See #5492 for a proposal to avoid the confusion going forward.

**Comment by munro-art** [comment]
does this mean ... as long as we do ConfigModule.withConfig **_AFTER_** then it will work?
`
@NgModule({
  imports: [

    B2cStorefrontModule,
    ConfigModule.withConfig({
        // custom config
   }),

})
export class AppModule {}
`

**Comment by tobi-or-not-tobi** [comment]
> does this mean ... as long as we do ConfigModule.withConfig AFTER then it will work?

correct!
