### ISSUE TITLE
Adaptive Search Profile is not applied on Category Page

### ISSUE THREAD

**Issue by mateuszburaczek** [SAP/cloud-commerce-spartacus-storefront#5510]
## Environment Details

- Spartacus:  1.2.0

## Steps to Reproduce

1. Prepare Category Aware Search Profile (to be done in Adaptive Search) with some configuration e.g promoted products.
2. Make sure configuration is synchronized to online catalog version.
3. Navigate to category with adaptive search changes applied.
4. Search Profile changes for category is not applied.

## Observed Results
Requests sent from spartacus does not narrow down search to category and rather treat category as facet.

## Expected Results
Category Aware Search Profile changes are applied Category Page

## Offer to Fix
No

## Additional Information
Simple Search Profile works fine. Problem is only occurring for Category Aware Search Profile.
On old storefront it works fine.

**Comment by Xymmer** [comment]
Potentially this seems to be a fix in backend Search API, creating ticket for backend search team

**Comment by KateChuen** [comment]
@Xymmer  to followup with backend team.

**Comment by neilhubertprice** [comment]
@Xymmer I have just taken a look at this because of a customer query.  The short version is: the Adaptive Search functionality on the backend looks for use of the _allCategories_ field, whereas Spartacus is currently using the _category_ field. 

You can see this in _DefaultSolrAsCategoryPathResolver.resolveCategoryPath()_ which is responsible for working out the category for the query, and from that the category path to the root category ... and this determines which Category Aware Search profiles are activated. If you follow the code through, it is looking first for a Filter Query against _allCategories_, then for a Facet Value against _allCategories_

If you look at the query that Spartacus issues, it is currently specifying a Facet Value against _category_ (query=:relevance:category:1360) whereas the old storefront accelerator applies a Filter Query against the _allCategories_ field when it constructs the query for a category page.  Where the comment above says 'On old storefront it works fine' ... that isn't really true.

**Comment by neilhubertprice** [comment]
I would need to modify product-list-component.service.ts to try this for real from Spartacus ... but if I modify the request manually in my browser to do query=:relevance:allCategories:1360, then the result set from OCC matches what I see via the old accelerator & products boosted for that specific category rise to the top

**Comment by neilhubertprice** [comment]
@Xymmer @tobi-or-not-tobi I just created a pull request to fix this item.  First time I have tried this for Spartacus so hopefully I have followed the guidelines correctly.  Not sure who I should ping to review this though?

**Comment by tobi-or-not-tobi** [comment]
@neilhubertprice nice one! I had fixed this in a local branch so can directly confirm you went right with your implementation. What I also remember however is that the breadcrumb is not returned with the response if you use `allCategories` relevance. We need an investigation on that one, as breadcrumb is currently a crucial part. Can you double check?

**Comment by neilhubertprice** [comment]
Ok, so I have also pushed a fix to the same branch for CategoryPageMetaResolver to understand the allCategories facet.

Note: Commerce setup needs modifying for this to work correctly.  The allCategories facet by default has no Facet Value Display Name Provider set.  Without that the breadcrumb displays the code rather than the name. Set this to the same as the category facet (categoryFacetDisplayNameProvider) to have proper names in the breadcrumb.

A couple of other points:
- I'm not sure the breadcrumb behaviour is ideal currently (I haven't modified the overall behaviour), as it shows breadcrumb links for any categories/brands chosen while filtering the result set.  This gives a non-intuitive list of breadcrumbs that links directly to the indivdual categories/brands .... really it probably ought to link to the search results with/without those filters.
- I haven't modified the test for CategoryPageMetaResolver, as it is out of date & only references the deprecated resolve() method

**Comment by tobi-or-not-tobi** [comment]
fixed with #6096, part of 2.0

**Comment by tobi-or-not-tobi** [comment]
sampledata change has already been added in https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/57
