### ISSUE TITLE
My Interests Feature Shown Even Though No Backend For it

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5572]
**Setup:**
1. Frontend branch feature/notification-preferences_my-interests_stock-notification branch
2. Backend deployed without necessary addons to support stock notification feature. (i.e. notificationoccaddon, customerinterestsoccaddon, stocknotificationservices)

**Steps to Reproduce:**
1. Navigate to dev-com6 and sign-in (deployed with
feature/notification-preferences_my-interests_stock-notification branch. )
1.a. http://dev-com-6.accdemo.b2c.ydev.hybris.com:4200/
2. From My Account, select My Interest. 

**Expected Result:** 
2. Message or text indicating feature is not available, and should be enabled in backend.... contact admin.

**Actual Results:**
2. The message "You have no registered interests yet" is misleading. The feature is in fact not available. It's not an empty list. It's a non-existent list. 
2.a. Can be inferred feature is not available given 404 from notificationpreferences API. 

![Screen Shot 2019-11-28 at 11 24 05 AM](https://user-images.githubusercontent.com/46171897/69821986-1f5a3a80-11d3-11ea-93d4-b2c2ddb55a4f.png)

**Comment by kate1zheng** [comment]
Hi GC, it is misconfiguration.
and I agree with you that if we can provide meaningful message when this kind of misconfiguration occurred.
however, it seems a general issue for SPA. if we configure a wrong occ API (e.g add a product to cart), it will have the following result:
![image](https://user-images.githubusercontent.com/43032959/69945333-4b075880-1524-11ea-84dd-fed76174a6e0.png)
you can see the xhr request is 404, but UI shows message 'items added to your cart'. in fact, the product is not added to cart.

and user may deploy the backend without any OCC API, then all requests in SPA will have 404, and all related UI should handle the error, that's why I say the error is a general issue, and should be handled in architect level, not case by case.

any suggestion from you?
Thanks
Kate

**Comment by Xymmer** [comment]
closing as stock notification is cms-based, you add or remove cms based on need for this feature
