### ISSUE TITLE
Release the Dec6 libs 

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#570]
Gil created a release branch Dec6
The smoke test passed, let's release the libs Monday Dec 10

**Comment by marlass** [comment]
Published new version of libs:
- `storefront` 0.1.0-prealpha.9 (latest) (was already published as next)
- `core` 0.1.0-prealpha.4 (latest)

styles were not changed, so I only changed `next` tag to `latest`.
removed old `next` tags

PR to merge release in master: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/571
Tag for `core` added: https://github.com/SAP/cloud-commerce-spartacus-storefront/tags
After merging release to master it should be also merged to develop, because of version bump for core library.

After that we should upgrade packages version in our main `package.json`

**Comment by marlass** [comment]
Released `storefront@0.1.0-prealpha.10` and checked shellapp. Everything seems to be working.

There are still steps that need to be done from comment above;
- Merge release branch into master and then develop. (I don't know if we should squash and merge this other option is not available for me).

I updated the dependencies in our root `package.json` in release branch, so only merge is required.

**Comment by hackergil** [comment]
Release branch merged to both master and develop
