### ISSUE TITLE
Site Context -> Currency & Language -> Checkout e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#5713]
Site context language checkout still failing, after general cart refactor e2e fix.

At _cypress/integration/regression/site-context/language/language-checkout.e2e-spec.ts_

Logs here: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/633/console

**Comment by bgambocjaviniar** [comment]
failing, will investigate why because 

<img width="1288" alt="Screen Shot 2019-12-09 at 1 46 47 PM" src="https://user-images.githubusercontent.com/29099466/70463294-a2f51080-1a8a-11ea-804f-111f6275ab42.png">


[language-checkout-page.e2e-spec.ts.mp4.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3941225/language-checkout-page.e2e-spec.ts.mp4.zip)

**Comment by bgambocjaviniar** [comment]
[HOLD] until fix is in develop

https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5663 --> only in release branch

https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5664 --> real fix coming soon

**Comment by giancorderoortiz** [comment]
Will this fix currency-checkout-page.e2e-spec.ts and language-checkout-page.e2e-spec.ts?

**Comment by giancorderoortiz** [comment]
Recording of site-context test execution here: 
[site-context.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3946053/site-context.zip)

**Comment by bgambocjaviniar** [comment]
Again to note* 
just adding wait to solidify each steps of checkout (bug still exists) --> Marcin has a solution to it which he will work on it soon for the develop branch

PR: GH-5739
