### ISSUE TITLE
Setup server to run all the e2e tests

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#590]
- Setup a server (use dev-com-20.accdemo.b2c.ydev.hybris.com)
-- an instance of spartacus running
--- that gets updated every night, before running the tests 
--- a shell script to update the libs from npm
--- that's similar to that of our customers

- We can use this server to debug the tests if required
- We can setup a cronjob to run all the tests every night
-- and maybe generate a report too?

**Comment by hackergil** [comment]
Here are my thoughts about this:
- Since dev20 is not accessible from the outside world, we'll have to setup a jenkins job for this. We can use our test or prod accelerators Jenkins for this.
- We can assume that the jenkins job will only run e2e tests (since Travis takes care of the code validation, tests, etc.)

And I have the following questions:
- Why do we want to update the libs from npm?
- What would we report on the suggested report?

**Comment by hackergil** [comment]
After #815 we don't need to do this anymore. Nightly builds will run on Travis.
