### ISSUE TITLE
applied promotions e2e tests failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6011]
applied promotions e2e tests are failing on dev-17. 

Logs here: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/724/consoleFull

<img width="1070" alt="Screen Shot 2020-01-07 at 3 47 01 PM" src="https://user-images.githubusercontent.com/30666844/71928174-fed3b780-3164-11ea-8678-483f23762460.png">

**Comment by Matejk00** [comment]
This ticket seems to be no longer valid, because we are not using dev-17 for e2e anymore.

After merge `feature/e2etests-1905.6` to `develop` there is only one failing e2e test regarding to applied promotions.

```
  1) Applied promotions Applied promotions as a logged user Should verify promotions in order confirmation details:
     CypressError: Timed out retrying: expected '<div.cx-promotions>' to contain 'EOS450D'
```

The problem is that currently applied promotions are not shown in the consigned entries. 
We created separate ticket to fix that #6428
