### ISSUE TITLE
XMLHttpRequest error when dynamically loading translations using SSR

### ISSUE THREAD

**Issue by arminh** [SAP/cloud-commerce-spartacus-storefront#6030]
## Environment Details

- Spartacus:  1.3.1
- Browser: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- OS: Ubuntu 18.04.3 LTS
- Device: Dell Precision-5530

## Steps to Reproduce
When loading translations dynamically according to the Spartacus documentation, Node.js throws an `XMLHttpRequest is not defined` error when using Server-Side Rendering:

1. Dynamically load translations
<pre>
<code>
18n: {
    backend: {
          loadPath: 'assets/translations/{{lng}}/{{ns}}.json',
        },
        chunks: translationChunksConfig,
        fallbackLang: 'en',
      },
..
</code></pre>
2. Activate Server-Side Rendering
3. Check Node console for Errors

## Observed Results
<pre>
<code>
ReferenceError: XMLHttpRequest is not defined
    at Object.ajax (/home/ahutzler/Work/ung-gui-2/dist/ung-rs/server.js:224212:5)
    at Backend.loadUrl (/home/ahutzler/Work/ung-gui-2/dist/ung-rs/server.js:224081:20)
    at Backend.read (/home/ahutzler/Work/ung-gui-2/dist/ung-rs/server.js:224074:12)
    at Connector.read (/home/ahutzler/Work/ung-gui-2/dist/ung-rs/server.js:223706:34)
    at Connector.loadOne (/home/ahutzler/Work/ung-gui-2/dist/ung-rs/server.js:223772:12)
    at /home/ahutzler/Work/ung-gui-2/dist/ung-rs/server.js:223745:16
    at Array.forEach (<anonymous>)
    at Connector.prepareLoading (/home/ahutzler/Work/ung-gui-2/dist/ung-rs/server.js:223744:21)
    at Connector.load (/home/ahutzler/Work/ung-gui-2/dist/ung-rs/server.js:223751:12)
    at I18n.loadResources (/home/ahutzler/Work/ung-gui-2/dist/ung-rs/server.js:221471:40)
</code>
</pre>

## Expected Results
Dynamically loading translation when using SSR without errors

**Comment by Platonn** [comment]
QA steps:
# Regression
## verify that static translations work as before:
1. run `yarn start` and verify that normal translations work as before

## veryify that dynamic translations work as before:
2. in app.module instead of `i18n.resources` set `i18n.backend.loadPath`, for example: `loadPath: 'assets/translations/{{lng}}/{{ns}}.json'`
3. generate JSON assets and copy to storefrontapp:
```
yarn build:assets
cp dist/assets/i18n-assets/ projects/storefrontapp/src/assets/ -r
```
4. run `yarn start` (if you have it already running, kill the previous process and run again)
5. verify that the translations are displayed properly and are coming via JSONs in the Network Devtools tab

# Bugfix
## veryify that dynamic translations work in SSR
6. disable PWA in spartacus config `pwa.enabled` - `false` (for convenience)
7. disable Javascript in your browser
8. kill previous webserver process and run SSR:
```
yarn build:core:lib
yarn build
yarn build:ssr
yarn start:ssr
```
9. Verify that translations are displayed in server side rendered pages
10. verify that no errors are thrown in the console of the SSR node process
