### ISSUE TITLE
[wait to test with GH-6051] Incorrect consignment labels

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#6049]
Set up new commerce api's (taken from 2005 release)
(I used OMS but Kate says the missing label happens with b2c_acc_cms)

1. Buy some products like (1 of each): 816261, 816323, 812888
2. Wait for consignments (1for each product)
3. Cancel one of the products

See below
- The cancelled product also says shipped
- The non-cancelled is displaying a localization code
![image](https://user-images.githubusercontent.com/4998145/72189785-c5e94c00-33cb-11ea-9f86-4600b3e1d929.png)

OMS setup
        extName 'ordermanagementaddon'
        extName 'ordermanagementfacades'
        extName 'ordermanagementwebservices'
        extName 'orderselfserviceaddon'

        extName 'warehousingbackoffice'
        extName 'warehousingfacades'
        extName 'warehousingwebservices'
        extName 'warehousing'

        extName 'yacceleratorordermanagement'

// must hide yacceleratorfulfillment

**Comment by Xymmer** [comment]
also class name fix from Tobias

**Comment by plabadie** [comment]
PR #6085

**Comment by Xymmer** [comment]
All labels and their texts:

  IN_TRANSIT = 'IN_TRANSIT',
In Transit

  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
Ready for Pickup

  READY_FOR_SHIPPING = 'READY_FOR_SHIPPING',
Ready for Shipping

  WAITING = 'WAITING',
Waiting

  DELIVERING = 'DELIVERING',
Delivering

  PICKPACK = 'PICKPACK',
Preparing for Shipment

  PICKUP_COMPLETE = 'PICKUP_COMPLETE',
Pickup Complete

  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
Delivery Complete

  PAYMENT_NOT_CAPTURED = 'PAYMENT_NOT_CAPTURED',
Payment Issue

  READY = 'READY',
Ready

  DELIVERY_REJECTED = 'DELIVERY_REJECTED',
Delivery Rejected

  SHIPPED = 'SHIPPED',
Shipped

  TAX_NOT_COMMITED = 'TAX_NOT_COMMITED',
Tax Issue

  CANCELLED = 'CANCELLED',
Cancelled

**Comment by plabadie** [comment]
I added the remaining labels.  I left those who were already defined as-is.
I also let `READY = 'In Process` to align with what Accelerator displays.

**Comment by KateChuen** [comment]
The misleading "Shipped" label is gone. Now the labels are mapped as such. One difference from what was mentioned is for the "Ready" status. "In Process" is displayed instead of "Ready" which is the same as before, so it's ok.


- [x] IN_TRANSIT -> In Transit
- [x] READY_FOR_PICKUP -> Ready for Pickup
- [x] READY_FOR_SHIPPING -> Ready for Shipping
- [x] WAITING -> Waiting
- [x] DELIVERING -> Delivering
- [x] PICKPACK -> Preparing for Shipment
- [x] PAYMENT_NOT_CAPTURED -> Payment Issue
- [x] READY -> In Process
- [x] DELIVERY_REJECTED -> Delivery Rejected
- [x] SHIPPED -> Shipped
- [x] TAX_NOT_COMMITED -> Tax Issue

- [x] PICKUP_COMPLETE -> Pickup Complete
- [x] DELIVERY_COMPLETED-> Delivery Complete

- [x] CANCELLED -> Cancelled
- [x] Pending
