### ISSUE TITLE
Revoke endpoint might not be available in older hybris version (applies to 1.4)

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#6255]
Pointed in slack: https://spartacus-storefront.slack.com/archives/CD16V16FR/p1580120124049400

Old instances don't have `revoke` endpoint and it might be useful to make it configurable.

The decision needs to be made about wrapping that in feature toggle

**Comment by plabadie** [comment]
Spartacus 1.4 is intended to be backwards compatible with backend versions that don’t support token revocation.

It is expected behaviour that with older than 1905.6 backends, Spartacus will still attempt a revocation request. There is logic in Spartacus to ignore the error of this request and Spartacus should fail silently.

See token revocation docs for details:
https://sap.github.io/cloud-commerce-spartacus-storefront-docs/token-revocation/#backend

If there is an issue we didn't foresee with attempting the revocation request on backends that don't support it,  or if in retrospect we think it would just be better to have a config to prevent the revocation requests from being made depending on the backend version,  we can open an issue to implement/fix it.
