### ISSUE TITLE
Spartacus not loading translations from local JSON files when using SSR

### ISSUE THREAD

**Issue by arminh** [SAP/cloud-commerce-spartacus-storefront#6307]
## Environment Details

- Spartacus: 1.4.0-rc.1
- Browser: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- OS: Ubuntu 18.04.3 LTS
- Device: Dell Precision-5530

## Steps to Reproduce

1. Create a new Angular application
2. Install Spartacus from the libraries using the schematic and the --ssr flag
3. Add config for loading translations from local files to the app.module
```
i18n: {
  backend: {
    loadPath: 'assets/translations/{{lng}}/{{ns}}.json',
  },
  chunks: translationChunksConfig,
  fallbackLang: 'en'
},
```
3. Build an run the SSR application using yarn build:ssr and yarn serve:ssr
4. Deactivate Javascript in the browser to see what is rendered on the server
5. Access a server-side rendered page(e.g.: Product Detail Page)

## Observed Results
The translations are not loaded by the Node application:
![image](https://user-images.githubusercontent.com/3740956/73337458-a9c32700-4274-11ea-897c-f676397fe8da.png)

## Expected Results
Translations should be loaded from JSON files also on initial server-side rendered page.

**Comment by tobi-or-not-tobi** [comment]
according to the feedback on stackoverflow, this still occurs on the 1.4 final.

**Comment by Platonn** [comment]
### The cause of problem
The problem is caused by the Angular Universal which doesn't allow for relative URLs in SSR (in `HttpClient`). See angular's issues:
- https://github.com/angular/angular/issues/19224
- https://github.com/angular/angular-cli/issues/25768

### Temporary workaround
Pass to the `loadPath` the an absolute path containing the host and the path.

### Proposed solution
Only in SSR: identify the server request's host. Then prepend this host to the relative path of `loadPath`. We should ensure that it's working also when having a reverse proxy (on a different host).

**Comment by Platonn** [comment]
### QA steps:
The same as here: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6030#issuecomment-573036540 **Please make sure to disable Javascript in your browser to see only the result of the SSR.**

Expected: translations are displayed on http://localhost:4200/electronics-spa/en/USD/product/300938/Photosmart%20E317%20Digital%20Camera (i.e. Add to cart button)

![image](https://user-images.githubusercontent.com/4001059/73747257-5dd21f80-4757-11ea-86ee-53a324f2bfba.png)
