### ISSUE TITLE
Apparel. Mobile. Empty Hamburger Menu

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#6353]
**Steps to Reproduce:** 

1. Navigate to Apparel store in a dev-server using Chrome
1.a. Such as http://dev-com-6.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/

2. Open dev tools and select mobile view. 

3. Select Iphone 6/7 device. 

4. in Spartacus Login as registered user

5. Click on hamburger menu. 

 **Expected results:** 
5. My account + product categories. 

**Actual Results:** 
5. Only MyAccount is shown in collapsed state. 

Apparel Store Hamburger Menu (Chrome -> Dev Tools -> Mobile -> iphone 6/7)
![Screen Shot 2020-01-31 at 3 25 34 PM](https://user-images.githubusercontent.com/46171897/73572722-813b5880-443f-11ea-8d9d-9aedadce86bb.png)

Electronics Store Hamburger Menu (Chrome -> Dev Tools -> Mobile -> iphone 6/7)

![Screen Shot 2020-01-31 at 3 27 12 PM](https://user-images.githubusercontent.com/46171897/73572748-91533800-443f-11ea-9534-0978543143bb.png)

**Comment by tobi-or-not-tobi** [comment]
There are different angles behind this issue: 
- The apparel sample data has a huge number of child navigations, this would not nicely fit on mobile anyway. Ideally there's adaptive content, or restrictions on mobile, or an alternative UI for mobile. We do not have this for now. 
- In order to wrap navigation lists after a certain amount of childs, the CMS provides a single "wrap" property for the navigation. This is set to 10 in case of apparel, which means it wraps after 10 childs. On desktop, this looks great, as there's good size to show 5 columns, but on mobile its failing hard
- given that we do not have a desktop vs mobile wrap property, we'll calculate the mobile based on the desktop.

**Comment by bgambocjaviniar** [comment]
QA STEPS: 

- Open dev tools and select mobile view or make the screen small
- Select Iphone 6/7 device or any small device

- check as anonymous and as a registered user
- click on hamburger menu, and verify that the category navigation nodes/links are there

**Comment by tobi-or-not-tobi** [comment]
QA – please not that this requires calydone theme

**Comment by KateChuen** [comment]
Tested on dev12. 
Now the menu is displayed, and we can navigate to them.

The only issue found was the header in one case: #6402
