### ISSUE TITLE
Create an out of stock product for e2e tests

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#6358]
Update the sample data to have a product that is out of stock for the cart test

**Comment by qjimmy** [comment]
Fix cart e2e test after this issue is closed. GH-6146

<img width="532" alt="Screen Shot 2020-01-31 at 4 16 42 PM" src="https://user-images.githubusercontent.com/30666844/73574948-0412e200-4445-11ea-803e-982d21fcbbef.png">

Product code is 872912. That product used to be out of stock and the test would pass, but not anymore.

**Comment by qjimmy** [comment]
Link to PR https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/71/files
