### ISSUE TITLE
accessibility: Focus displayed after drop down menu on firefox

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#6514]
**Environment Details**
Spartacus: epic/accessibility branch
Browser: Firefox
Device: mac
Happens on: http://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Tab on the Header Category, Brands for eg.
- Press TAB  again -> The focus is on something empty? We see it whenever there's a drop down menu. 
Therefore, after tabbing on MyAccount, Brands, Digital Cameras etc

<img width="1226" alt="Screen Shot 2020-02-12 at 1 48 13 PM" src="https://user-images.githubusercontent.com/45409515/74367045-2ee32b80-4d9f-11ea-8aa3-ed64857b1966.png">
<img width="1255" alt="Screen Shot 2020-02-12 at 1 51 30 PM" src="https://user-images.githubusercontent.com/45409515/74367047-2ee32b80-4d9f-11ea-9319-3038df42f357.png">

**Comment by developpeurweb** [comment]
**Note for devs:** This is related to an empty `<span>` in the navigation, we (Kacper, Caine, Miguel) have agreed to tackle this when the **cx-category-navigation** gets refactored, as there are currently other issues to be fixed in there as well.

![Screen Shot 2020-02-18 at 4 00 03 PM](https://user-images.githubusercontent.com/15113219/74778838-6738ad00-526a-11ea-8e5f-26b4ab5c9109.png)

**Comment by developpeurweb** [comment]
This is related to GH-6310

**Comment by kacperknapik** [comment]
This problem is already addressed with the latest changes to a11y epic branch.
