### ISSUE TITLE
Issue Overwriting Translations

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#6573]
I reproduced part of an issue reported on the public slack.

https://spartacus-storefront.slack.com/archives/CD16V16FR/p1581625216291600?thread_ts=1581624935.291500&cid=CD16V16FR

Reading the Spartacus i18n doc:
https://sap.github.io/cloud-commerce-spartacus-storefront-docs/i18n
See the section called: `How to overwrite individual translations`

It seems that doing the following should work:

Have for example a `MyTranslationModule` module in your app:

`MyTranslationModule`:
```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ConfigModule } from '@spartacus/core';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    ConfigModule.withConfig({
      i18n: {
        resources: {
          en: {
            common: {
              miniLogin: {
                signInRegister: 'Translation Overwritten!!',
              },
            },
          },
        },
      },
    }),
  ],
})
export class MyTranslationModule {}
```

And then import `MyTranslationModule` last in `AppModule`

`AppModule`
```
@NgModule({
    imports: [
      ...
      B2cStorefrontModule.withConfig({
        ...
      }),
      ...
      MyTranslationModule,
    ],
 ... 
```

That doesn't work.

What does work however, is the exact same `ConfigModule.withConfig` import but placed directly in `AppModule` instead of importing `MyTranslationModule`

`AppModule`:
```
@NgModule({
    imports: [
      ...
      B2cStorefrontModule.withConfig({
        ...
      }),
      ...
      ConfigModule.withConfig({
        i18n: {
          resources: {
            en: {
              common: {
                miniLogin: {
                  signInRegister: 'Translation Overwritten!!',
                },
              },
            },
          },
        },
      }),
    ],
 ... 
```

Workaround and issue reproduced on branch `release/1.5.x` with a contributor setup against dev12 backen.

<img width="339" alt="i18n-overwrite" src="https://user-images.githubusercontent.com/7065346/74556779-c7f37d00-4f2c-11ea-9f29-dd624206d33f.png">

**Comment by dunqan** [comment]
I'm afraid it's by design. Config provided at the top-level module will overwrite one provided on a lower level (in a submodule) even if that submodule was imported later. It's how DI and providers in Angular works in general,

I guess that:
```
      B2cStorefrontModule.withConfig({
        ...
      }),
```
placed in app.module actually contains the override of `i18n.resources`.

The issue is about providing the same config at different levels:: the first one is in app.module, and the second one is in a module imported in app.module thus the second one is overwritten by the first.

The solution for it is either as explained in the description, provide both configs in app.module directly 
OR move 
```
   {
        i18n: { resources: translations }
    }
```
also to submodule (could be even to MyTranslationsModule).

**Comment by rue-bkeeter** [comment]
@dunqan - do our CMS component override configurations work when specified in the sub-module because we don't specify any in the app module? It would definitely be preferable to keep our overrides local to the module that needs them, but it would appear that if my assumption above is true then a customer i18n module that owned the original configuration and any overrides would be the best approach?

**Comment by tobi-or-not-tobi** [comment]
See #5492 for a solution to this problem.

**Comment by plabadie** [comment]
Since improvements to the underlying config mechanism is in scope of an existing ticket (GH-5492), I will close this ticket.  Short term, a doc improvement could help avoiding the pitfall described in the present ticket.
https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/521

**Comment by rue-bkeeter** [comment]
@tobi-or-not-tobi @plabadie I guess I don't see how #5492 is going to help this. We are already loading our module config after the B2CStorefront config (otherwise other module features wouldn't work).

**Comment by rue-bkeeter** [comment]
The way I see to do this "correctly" is have all of our i18n setup in one module, we can't piecemeal it across our submodules (which would make it a little easier to manage).

> The solution for it is either as explained in the description, provide both configs in app.module directly
OR move
   > {
        i18n: { resources: translations }
    }
> also to submodule (could be even to MyTranslationsModule).
