### ISSUE TITLE
Buttons and Input Field in Cart not usable

### ISSUE THREAD

**Issue by Darius998** [SAP/cloud-commerce-spartacus-storefront#6739]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  1.5.0
- Browser: Chrome 80
- OS: Windows 10 (1909)
- Device: 
- Other environment details: 
Angular 8.2.8, 
features.level = 1.5, 
pwa.enabled = false,
started with "yarn start --ssl" (no ssr)

## Steps to Reproduce
Add something to shopping cart and try to modífy quantity, remove or save for later

## Observed Results
All buttons are disabled
![chrome_T3Yf6JhJ72](https://user-images.githubusercontent.com/45655339/75539927-5bdc4300-5a1b-11ea-8813-37ae7b2282be.png)

## Expected Results
Buttons should be usable and do their thing

**Comment by Platonn** [comment]
Conversation in public slack: https://spartacus-storefront.slack.com/archives/CD16V16FR/p1582881814073600

**Comment by LTiger14** [comment]
This might be related to your backend version. @Darius998 what version of Commerce are you running?

**Comment by LTiger14** [comment]
Regardless of if this is a version issue or not Spartacus should support 1905 as a whole. Certain feature might require a specific version (1905.11 for customer coupons) but the site should not break if the version does not support the feature.

We should handle gracefully these errors so that Spartacus is still usable.

**Comment by psmul** [comment]
The problem shows up for every situation where there is no response from the server. Nor Chrome or Firefox are returning any status when they lose connection to the internet, thus inputs/buttons stay blocked due to flag `cartLoaded$` not returning/changing its state. 
The issue should be resolved application-wide, maybe with adding an additional interceptor for simple connection checks, which in the case will throw an observable error. 
Any thoughts @dunqan @tobi-or-not-tobi ?

**Comment by tobi-or-not-tobi** [comment]
@LTiger14  If there's no backend response, in this case for the cartLoaded$ state, I think it's correct to not enable the input, as otherwise you could post data without the context of the cart, which results in strange errors. 

I agree to @psmul that we could have an application wide (x-times) retry. I wonder why the error handling doesn't kick in, in this specific case. Can you double check this?

**Comment by psmul** [comment]
QA steps:

- log in and add item to cart
- open dev tools
- go into Offline mode
- try to raise product count in your cart

Expected result:
- counter shouldn't be blocked
- in console you should ge warning about Unknown error -1

(There is an issue that counter will still provide new value but it's only on view layer, no data on backend will be updated)

**Comment by Matejk00** [comment]
QA done:
- counter is not blocked anymore in offline mode
- there are warnings about Unknown error -1 in a console
