### ISSUE TITLE
Create store finder e2e test

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#736]
- Test Store Finder button
Click on the “store finder icon” -> Land on “Find a store” page

- Test search store
Search “Tokyo”, click on “Find Stores button”

Verify results:
1-10 from 49 stores found
First store highlighted
First store is Sapporo Sheraton Sapporo Hotel
Store image & address listed (where applicable)
A google map displayed (where applicable)
Store hours displayed
Store feature displayed

- Test Pagination on the search result
Click on Next , Next, Previous

- Test selecting other stores from the list

- Test searching for other location, for eg “New York” and click on the “search button”

**Comment by kacperknapik** [comment]
@wishfulthinkerme are you sure all of the tests in the ticket description are implemented?

**Comment by wishfulthinkerme** [comment]
The main that isn't implemented is searching. It is waiting for https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/751, as I cannot search.

**Comment by mszczepaniak** [comment]
Blocked until #992 is fixed

**Comment by Xymmer** [comment]
Looks like we're blocked because the Walkers changed 2 endpoints
count to storescount
the other was....

this works on newer servers but modelt is out of date.

**Comment by marlass** [comment]
Issues found while working on e2e tests:
- we no longer have a link to store finder in header (access only by url)
- search returns the same results every time (#1372)
- on mobile there is pagination under map view

Previous tests requirements:
- [ ] 1-10 from 49 stores found (no such information on page)
- [x] 20 results found (pagination set to 20 stores per page)
- [ ] First store highlighted (store is not highlighted)
- [x] First store is Sapporo Sheraton Sapporo Hotel (store changed)
- [x] Store image & address listed (where applicable) (we don't display images)
- [x] A google map displayed (where applicable)
- [x] Store hours displayed (test disabled, because of outdated modelt server)
- [x] Store feature displayed (test disabled, because of outdated modelt server)
- [x] Test Pagination on the search result (next, previous, by number)
- [x] Test selecting other stores from the list
- [ ] Test searching for other location, for eg “New York” and click on the “search button” (search returns always the same list)

**Comment by kacperknapik** [comment]
@Xymmer can you take a look at the above checkboxes - some of the functionalities are not there or are blocked and we don't really know if we should implement the tests or go without them

**Comment by Xymmer** [comment]
we agreed to move the 3 unfinished tests to next phase of storefinder work (styling update, bug fixes) (FR2)
