### ISSUE TITLE
[CAN'T REPRODUCE] Form stops displaying when creating shipping address

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#758]
From #730 - smoke testing Dec 18 lib release
After creating a Shipping Address, (moving on to step 2: Shipping Method), I was not able to continue. When I wen't back to Step 1: Shipping Address, nothing appears and now I am stuck

**Comment by marlass** [comment]
Wasn't able to reproduce that behavior. Tried that on account with some shipping addresses defined and it worked there. On a fresh account, it also worked without problems.

I assume it happened, because of some connection problem, request failure. We can implement some retries, but it should be done in whole checkout, not only this step.

**Comment by Xymmer** [comment]
moving this one back to triage to decide if it's worth adding retry as suggested

**Comment by Xymmer** [comment]
fixed as part of #1248 by tobias
