### ISSUE TITLE
Build in pixel ratio detection for images

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#899]
As per discussion with Bill we need to come up with the best way to handle pixel ratio detection (ex. retina displays)
Maybe start by checking out how it's done in Accelerator and SmartEdit implications.
@Xymmer can you please label this ticket and place in the right board.

**Comment by tobi-or-not-tobi** [comment]
I've actually implemented this in the original image component. It's using the [html5 picture](https://www.w3schools.com/tags/att_source_srcset.asp) element with sources related to specific srcsets. Since our medias come with different formats, it aligns very nicely with this standard. 
I'm not sure why this was left out, but you can actually still see the code, it's commented out. 

@Xymmer can you recall the reasoning why it's removed?

**Comment by tobi-or-not-tobi** [comment]
closed with #2234

**Comment by Xymmer** [comment]
i don't know why it was commented out
it's back now though?

**Comment by tobi-or-not-tobi** [comment]
Correct, but we've changed the implementation.

**Comment by Xymmer** [comment]
How to test?

**Comment by tobi-or-not-tobi** [comment]
QA Steps:
- change the images in an single image container for different formats, so that you can see the differences per size
- verify that the the different images show up at different breakpoints

**Comment by Xymmer** [comment]
Banners are working as intended. There are follow up questions but that’ll be new issues

**Comment by Xymmer** [comment]
Assigning to Tobias for doc check
